import { FormConfig } from './route';

export const coordinationFeeCourseClosureConfig: FormConfig = {
    title: "COORDINATION FEE AND COURSE CLOSURE FORM",
    subtitle: "FOR OPEN PARTICIPATION/SPONSORED COURSE FUND",
    fields: [
        { label: "Course-Code.", value: "", type: "text" },
        { label: "Distribution: Final/Interim", value: "", type: "text" },
        { label: "Title of Course", value: "", type: "text" },
        { label: "Course Coordinator's/PI's Name", value: "", type: "text" },
        { label: "Designation", value: "", type: "text" },
        { label: "Department /Centre", value: "", type: "text" },
        { label: "A. COURSE FUND POSITION", value: "", type: "text" },
        { label: "a. Gross amount including GST G", value: "", type: "text" },
        { label: "b. Less GST as applicable L (presently @18%) (G/1.18*18%)", value: "", type: "text" },
        { label: "c. Total Contracted amount T (=G-L)", value: "", type: "text" },
        { label: "d. Amount payable to Institute Overhead Charges P (@20%of T)", value: "", type: "text" },
        { label: "e. CEC operational/establishment cost O(@10%of T-P)", value: "", type: "text" },
        { label: "f. TDS Deduction (if any) TD", value: "", type: "text" },
        { label: "g. Honorarium to Instructor/s/Experts H", value: "", type: "text" },
        { label: "h. Expenditure already done E", value: "", type: "text" },
        { label: "i. Balance amount available (T-P-O-TD-H-E)", value: "", type: "text" },
        { label: "B. Details of amount to be distributed", value: "", type: "text" },
        { label: "i. CEC DDF component CEC-DDF-001 (in case of Open Participation course, if coordination fee amount is above Rs. 8 Lacs)", value: "", type: "text" },
        { label: "ii. Coordination fee C max@20% of 20% of (T-P)* (Note: whole or part can be transferred to PDF)", value: "", type: "text" },
        { label: "Details of distribution among Coordinators", value: "", type: "text" },
        { label: "Mention all the names as per approval even if the amount to be disbursed is NIL.", value: "", type: "text" },
        { label: "Name", value: "", type: "text" },
        { label: "Employee code", value: "", type: "text" },
        { label: "Bank A/C No.", value: "", type: "text" },
        { label: "IFSC Code:", value: "", type: "text" },
        { label: "PDF", value: "", type: "text" },
        { label: "Amount Rs. \n Bank A/C", value: "", type: "text" },
        { label: "Remaining amount (if any) to DDF of CEC [CEC-DDF-001] =", value: "", type: "text" },
        { label: "Certified that", value: "", type: "text" },
        { label: "This is final distribution and that the work has been completed. The final report has been sent vide letter No. _____________ Dated ____________ (Copy enclosed)", value: "", type: "text" },
        { label: "The soft copy of the following documents are required :", value: "", type: "text" },
        { label: "(i) Name, email id and address of the sponsoring agency", value: "", type: "text" },
        { label: "(ii) List of experts with email id and address", value: "", type: "text" },
        { label: "(iii) List of the participants with email id and address", value: "", type: "text" },
        { label: "(iv) Time Table", value: "", type: "text" },
        { label: "(v) Group-photo.", value: "", type: "text" },
        { label: "Signature of the Course Coordinator (with date)", value: "", type: "text" },
        { label: "Extn. (O)__________Mobile__________", value: "", type: "text" },
        { label: "Email :_________________________", value: "", type: "text" },
        { label: "Endorsement by CEC/SRIC Office, I.I.T. Roorkee", value: "", type: "text" },
        { label: "The above is submitted for approval as recommended by Coordinator, CEC", value: "", type: "text" },
        { label: "Recommended /Not Recommended", value: "", type: "text" },
        { label: "Approved/Not Approved", value: "", type: "text" },
        { label: "D.A /Sr. Supdt. C.E.C.", value: "", type: "text" },
        { label: "Coordinator, CEC", value: "", type: "text" },
        { label: "D.A. /Supdt. SRIC", value: "", type: "text" },
        { label: "A.R./Dy. Registrar (SRIC)                    Dean, SRIC", value: "", type: "text" },
        { label: "Distribution of total institute share into IDF/CEC DDF Account , Total Institute Overhead Charges deducted (P)", value: "", type: "text" },
        { label: "(i) 50% to IDF [CEC-IDF-001]", value: "", type: "text" },
        { label: "(ii) 45% to CEC [CEC-DDF-001]", value: "", type: "text" },
        { label: "(iii) 5% Electricity [CEC-DDF-001]", value: "", type: "text" },
        { label: "Coordinator, CEC", value: "", type: "text" },
        { label: "* Coordination Fee", value: "", type: "text" },
        { label: "(i) Open Participation Course", value: "", type: "text" },
        { label: "Coordination Fee (Open Participation): Max Rs. 8 Lakh. 50% of excess above Rs. 8 Lakhs to faculty PDF, 50% to CEC corpus.", value: "", type: "multiline" },
        { label: "(ii) Sponsored Course", value: "", type: "text" },
        { label: "Coordination Fee (Sponsored): Max Rs. 8 Lakh. Excess above Rs. 8 Lacs to faculty PDF.", value: "", type: "multiline" }
    ],
    multilineFields: [
        { label: "Coordination Fee (Open Participation): Max Rs. 8 Lakh. 50% of excess above Rs. 8 Lakhs to faculty PDF, 50% to CEC corpus.", value: "", maxWidth: 400 },
        { label: "Coordination Fee (Sponsored): Max Rs. 8 Lakh. Excess above Rs. 8 Lacs to faculty PDF.", value: "", maxWidth: 400 }
    ]
};

export const mapCoordinationFeeCourseClosureDataToConfig = (formData: any): FormConfig => {
    return {
        ...coordinationFeeCourseClosureConfig,
        fields: [
            { label: "Course-Code.", value: formData.course_code || "", type: "text" },
            { label: "Distribution: Final/Interim", value: formData.distribution || "", type: "text" },
            { label: "Title of Course", value: formData.title_of_course || "", type: "text" },
            { label: "Course Coordinator's/PI's Name", value: formData.coordinator_name || "", type: "text" },
            { label: "Designation", value: formData.designation || "", type: "text" },
            { label: "Department /Centre", value: formData.department || "", type: "text" },
            { label: "A. COURSE FUND POSITION", value: "", type: "text" },
            { label: "a. Gross amount including GST G", value: formData.gross_amount?.toString() || "", type: "text" },
            { label: "b. Less GST as applicable L (presently @18%) (G/1.18*18%)", value: formData.less_gst?.toString() || "", type: "text" },
            { label: "c. Total Contracted amount T (=G-L)", value: formData.total_contracted?.toString() || "", type: "text" },
            { label: "d. Amount payable to Institute Overhead Charges P (@20%of T)", value: formData.overhead_charges?.toString() || "", type: "text" },
            { label: "e. CEC operational/establishment cost O(@10%of T-P)", value: formData.cec_operational_cost?.toString() || "", type: "text" },
            { label: "f. TDS Deduction (if any) TD", value: formData.tds_deduction?.toString() || "", type: "text" },
            { label: "g. Honorarium to Instructor/s/Experts H", value: formData.honorarium?.toString() || "", type: "text" },
            { label: "h. Expenditure already done E", value: formData.expenditure_done?.toString() || "", type: "text" },
            { label: "i. Balance amount available (T-P-O-TD-H-E)", value: formData.balance_amount?.toString() || "", type: "text" },
            { label: "B. Details of amount to be distributed", value: "", type: "text" },
            { label: "i. CEC DDF component CEC-DDF-001 (in case of Open Participation course, if coordination fee amount is above Rs. 8 Lacs)", value: formData.cec_ddf_component?.toString() || "", type: "text" },
            { label: "ii. Coordination fee C max@20% of 20% of (T-P)* (Note: whole or part can be transferred to PDF)", value: formData.coordination_fee?.toString() || "", type: "text" },
            { label: "Details of distribution among Coordinators", value: "", type: "text" },
            { label: "Mention all the names as per approval even if the amount to be disbursed is NIL.", value: "", type: "text" },
            { label: "Name", value: formData.distribution_name_1 || "", type: "text" },
            { label: "Employee code", value: formData.distribution_employee_code_1 || "", type: "text" },
            { label: "Bank A/C No.", value: formData.distribution_bank_ac_no_1 || "", type: "text" },
            { label: "IFSC Code:", value: formData.distribution_ifsc_code_1 || "", type: "text" },
            { label: "PDF", value: formData.distribution_pdf_1 || "", type: "text" },
            { label: "Amount Rs. \n Bank A/C", value: formData.distribution_amount_1?.toString() || "", type: "text" },
            { label: "Remaining amount (if any) to DDF of CEC [CEC-DDF-001] =", value: formData.remaining_amount?.toString() || "", type: "text" },
            { label: "Certified that", value: "", type: "text" },
            { label: "This is final distribution and that the work has been completed. The final report has been sent vide letter No. _____________ Dated ____________ (Copy enclosed)", value: "", type: "text" },
            { label: "The soft copy of the following documents are required :", value: "", type: "text" },
            { label: "(i) Name, email id and address of the sponsoring agency", value: "", type: "text" },
            { label: "(ii) List of experts with email id and address", value: "", type: "text" },
            { label: "(iii) List of the participants with email id and address", value: "", type: "text" },
            { label: "(iv) Time Table", value: "", type: "text" },
            { label: "(v) Group-photo.", value: "", type: "text" },
            { label: "Signature of the Course Coordinator (with date)", value: "", type: "text" },
            { label: "Extn. (O)__________Mobile__________", value: "", type: "text" },
            { label: "Email :_________________________", value: "", type: "text" },
            { label: "Endorsement by CEC/SRIC Office, I.I.T. Roorkee", value: "", type: "text" },
            { label: "The above is submitted for approval as recommended by Coordinator, CEC", value: "", type: "text" },
            { label: "Recommended /Not Recommended", value: "", type: "text" },
            { label: "Approved/Not Approved", value: "", type: "text" },
            { label: "D.A /Sr. Supdt. C.E.C.", value: "", type: "text" },
            { label: "Coordinator, CEC", value: "", type: "text" },
            { label: "D.A. /Supdt. SRIC", value: "", type: "text" },
            { label: "A.R./Dy. Registrar (SRIC)                    Dean, SRIC", value: "", type: "text" },
            { label: "Distribution of total institute share into IDF/CEC DDF Account , Total Institute Overhead Charges deducted (P)", value: formData.dist_to_idf?.toString() || "", type: "text" },
            { label: "(i) 50% to IDF [CEC-IDF-001]", value: formData.dist_50_idf?.toString() || "", type: "text" },
            { label: "(ii) 45% to CEC [CEC-DDF-001]", value: formData.dist_45_cec?.toString() || "", type: "text" },
            { label: "(iii) 5% Electricity [CEC-DDF-001]", value: formData.dist_5_electricity?.toString() || "", type: "text" },
            { label: "Coordinator, CEC", value: "", type: "text" },
            { label: "* Coordination Fee", value: "", type: "text" },
            { label: "(i) Open Participation Course", value: "", type: "text" },
            { label: "Coordination Fee (Open Participation): Max Rs. 8 Lakh. 50% of excess above Rs. 8 Lakhs to faculty PDF, 50% to CEC corpus.", value: "", type: "multiline" },
            { label: "(ii) Sponsored Course", value: "", type: "text" },
            { label: "Coordination Fee (Sponsored): Max Rs. 8 Lakh. Excess above Rs. 8 Lacs to faculty PDF.", value: "", type: "multiline" }
        ],
        multilineFields: [
            { label: "Coordination Fee (Open Participation): Max Rs. 8 Lakh. 50% of excess above Rs. 8 Lakhs to faculty PDF, 50% to CEC corpus.", value: "", maxWidth: 400 },
            { label: "Coordination Fee (Sponsored): Max Rs. 8 Lakh. Excess above Rs. 8 Lacs to faculty PDF.", value: "", maxWidth: 400 }
        ]
    };
};
