import { FormConfig } from './route';

export const courseClosingOldConfig: FormConfig = {
    title: "PROPOSAL FOR DISTRIBUTION OF HRD/ CONSULTANCY COURSE FUND",
    subtitle: undefined,
    fields: [
        { label: "Project No.", value: "", type: "text" },
        { label: "Distribution:", value: "", type: "text" },
        { label: "Title of Project:", value: "", type: "text" },
        { label: "PI's Name", value: "", type: "text" },
        { label: "Designation", value: "", type: "text" },
        { label: "Department/Centre", value: "", type: "text" },
        { label: "A. PROJECT FUND POSITION", value: "", type: "text" },
        { label: "Gross amount including service tax 'G'", value: "", type: "text" },
        { label: "Less GST as applicable 'L' (presently @18%)", value: "", type: "text" },
        { label: "Total Contracted amount 'T' (=G-L)", value: "", type: "text" },
        { label: "Amount payable to Institute (Institute Share) 'P' (@20%T)", value: "", type: "text" },
        { label: "Remaining amount 'F'( = T-P) (@80%T)", value: "", type: "text" },
        { label: "Expenditure already done 'E'", value: "", type: "text" },
        { label: "Balance Amount for Distribution 'S' = F-E", value: "", type: "text" },
        { label: "B. DETAILS OF AMOUNT TO BE DISTRIBUTED, 'S'", value: "", type: "text" },
        { label: "Coordination Fee 'C'(= maximum 20% of 'F')", value: "", type: "text" },
        { label: "Details of distribution among Coordinators, Technical and other staff", value: "", type: "text" },
        { label: "Mention all the names as per approval even if the amount to be disbursed is NIL.", value: "", type: "text" },
        { label: "Name", value: "", type: "text" },
        { label: "Designation", value: "", type: "text" },
        { label: "Employee code", value: "", type: "text" },
        { label: "Bank A/C No.", value: "", type: "text" },
        { label: "Amount Rs.", value: "", type: "text" },
        { label: "Income tax", value: "", type: "text" },
        { label: "Net amount", value: "", type: "text" },
        { label: "Token no.", value: "", type: "text" },
        { label: "Remaining amount (if any) to DDF of CEC", value: "", type: "text" },
        { label: "Certified that", value: "", type: "text" },
        { label: "(a) The amount distributed is within the prescribed limit for each individual.", value: "", type: "text" },
        { label: "(b1) This is interim distribution and the percentage of amount of work done against the consultancy project is not less than the corresponding percentage of the consultancy fee being distributed now.", value: "", type: "text" },
        { label: "(b2) This is final distribution and that the work has been completed. The final report has been sent vide letter No. __________ Dated __________ (Copy enclosed)", value: "", type: "text" },
        { label: "The following documents will be required at the closing time of the course in CD/Pen-Drive:", value: "", type: "text" },
        { label: "1. Name and address, phone, fax etc. of the sponsoring agency.", value: "", type: "text" },
        { label: "2. List of the internal and outside faculty/experts with address", value: "", type: "text" },
        { label: "3. List of the participants with full address.", value: "", type: "text" },
        { label: "4. Time Table copy", value: "", type: "text" },
        { label: "5. Copy of the group-photo.", value: "", type: "text" },
        { label: "Signature of the Course Coordinator (with date)", value: "", type: "text" },
        { label: "Extn. (O)", value: "", type: "text" },
        { label: "Mobile", value: "", type: "text" },
        { label: "Email :", value: "", type: "text" },
        { label: "Endorsement by CEC /SRIC Office, I.I.T. Roorkee", value: "", type: "text" },
        { label: "The above is submitted for approval as recommended by Course Coordinator", value: "", type: "text" },
        { label: "Recommended/Not Recommended", value: "", type: "text" },
        { label: "Approved/Not Approved", value: "", type: "text" },
        { label: "D.A. /Sr.Supdt. C.E.C.", value: "", type: "text" },
        { label: "Coordinator, CEC", value: "", type: "text" },
        { label: "D.A. /Supdt. SRIC", value: "", type: "text" },
        { label: "A.R./Dy. Registrar (SRIC)", value: "", type: "text" },
        { label: "Dean, SRIC", value: "", type: "text" },
        { label: "For distribution of total Institute share into IDF/CEC Account . DDF, PDF and incentive to staff, SWF etc. on getting full payment only at the time of closing the project (on final distribution only):", value: "", type: "text" },
        { label: "Total Institute Share deducted (P)", value: "", type: "text" },
        { label: "(a) RDF (CEC Account ) [CED-IDF-001]", value: "", type: "text" },
        { label: "50% of P", value: "", type: "text" },
        { label: "(b) DDF of CEC [CEC-DDF-001]", value: "", type: "text" },
        { label: "15% of P", value: "", type: "text" },
        { label: "(c) Electricity Charges [CEC-DDF-001]", value: "", type: "text" },
        { label: "5% of P", value: "", type: "text" },
        { label: "(d) PDF", value: "", type: "text" },
        { label: "25 % of P", value: "", type: "text" },
        { label: "(i) PDF of Dr. ", value: "", type: "text" },
        { label: "(ii) PDF of Dr. ", value: "", type: "text" },
        { label: "(iii) PDF of Dr. ", value: "", type: "text" },
        { label: "Total", value: "", type: "text" },
        { label: "Distribution of incentive to office staff and SWF etc. ...5.% etc. ........ of P", value: "", type: "text" },
        { label: "(i) Staff Welfare Fund", value: "", type: "text" },
        { label: "(5%)", value: "", type: "text" },
        { label: "(ii) Departmental Office", value: "", type: "text" },
        { label: "(20%)", value: "", type: "text" },
        { label: "(iii) CEC Staff", value: "", type: "text" },
        { label: "(30%)", value: "", type: "text" },
        { label: "(iv) Fund for Community Activities", value: "", type: "text" },
        { label: "(10%)", value: "", type: "text" },
        { label: "(v) Central Administrative Fund", value: "", type: "text" },
        { label: "(35%)", value: "", type: "text" },
        { label: "(Signature of Course Coordinator)", value: "", type: "text" },
        { label: "No. CEC/", value: "", type: "text" },
        { label: "Dated:", value: "", type: "text" },
        { label: "Copy forwarded for taking further action to:", value: "", type: "text" },
        { label: "1. Professor & Head", value: "", type: "text" },
        { label: "2. Principal Investigator", value: "", type: "text" },
        { label: "3. Professor-in-Charge (Finance) O.S. Pay roll for information and n.a. please", value: "", type: "text" },
        { label: "4. Section In charge, CEC", value: "", type: "text" },
        { label: "5. Distribution Folder", value: "", type: "text" },
        { label: "Coordinator, CEC", value: "", type: "text" }
    ],
    multilineFields: []
};

export const mapCourseClosingOldDataToConfig = (formData: any): FormConfig => {
    return {
        ...courseClosingOldConfig,
        fields: [
            { label: "Project No.", value: formData.project_no || "", type: "text" },
            { label: "Distribution:", value: formData.distribution || "", type: "text" },
            { label: "Title of Project:", value: formData.project_title || "", type: "text" },
            { label: "PI's Name", value: formData.pi_name || "", type: "text" },
            { label: "Designation", value: formData.designation || "", type: "text" },
            { label: "Department/Centre", value: formData.department || "", type: "text" },
            { label: "A. PROJECT FUND POSITION", value: "", type: "text" },
            { label: "Gross amount including service tax 'G'", value: formData.gross_amount?.toString() || "", type: "text" },
            { label: "Less GST as applicable 'L' (presently @18%)", value: formData.less_gst?.toString() || "", type: "text" },
            { label: "Total Contracted amount 'T' (=G-L)", value: formData.total_contracted?.toString() || "", type: "text" },
            { label: "Amount payable to Institute (Institute Share) 'P' (@20%T)", value: formData.institute_share?.toString() || "", type: "text" },
            { label: "Remaining amount 'F'( = T-P) (@80%T)", value: formData.remaining_amount?.toString() || "", type: "text" },
            { label: "Expenditure already done 'E'", value: formData.expenditure_done?.toString() || "", type: "text" },
            { label: "Balance Amount for Distribution 'S' = F-E", value: formData.balance_amount?.toString() || "", type: "text" },
            { label: "B. DETAILS OF AMOUNT TO BE DISTRIBUTED, 'S'", value: "", type: "text" },
            { label: "Coordination Fee 'C'(= maximum 20% of 'F')", value: formData.coordination_fee?.toString() || "", type: "text" },
            { label: "Details of distribution among Coordinators, Technical and other staff", value: "", type: "text" },
            { label: "Mention all the names as per approval even if the amount to be disbursed is NIL.", value: "", type: "text" },
            { label: "Distribution Details:", value: "", type: "text" },
            { label: "Name", value: formData.distribution_name_1 || "", type: "text" },
            { label: "Designation", value: formData.distribution_designation_1 || "", type: "text" },
            { label: "Employee code", value: formData.distribution_employee_code_1 || "", type: "text" },
            { label: "Bank A/C No.", value: formData.distribution_bank_ac_1 || "", type: "text" },
            { label: "Amount Rs.", value: formData.distribution_amount_1?.toString() || "", type: "text" },
            { label: "Income tax", value: formData.distribution_income_tax_1?.toString() || "", type: "text" },
            { label: "Net amount", value: formData.distribution_net_amount_1?.toString() || "", type: "text" },
            { label: "Token no.", value: formData.distribution_token_no_1 || "", type: "text" },
            { label: "Name", value: formData.distribution_name_2 || "", type: "text" },
            { label: "Designation", value: formData.distribution_designation_2 || "", type: "text" },
            { label: "Employee code", value: formData.distribution_employee_code_2 || "", type: "text" },
            { label: "Bank A/C No.", value: formData.distribution_bank_ac_2 || "", type: "text" },
            { label: "Amount Rs.", value: formData.distribution_amount_2?.toString() || "", type: "text" },
            { label: "Income tax", value: formData.distribution_income_tax_2?.toString() || "", type: "text" },
            { label: "Net amount", value: formData.distribution_net_amount_2?.toString() || "", type: "text" },
            { label: "Token no.", value: formData.distribution_token_no_2 || "", type: "text" },
            { label: "Name", value: formData.distribution_name_3 || "", type: "text" },
            { label: "Designation", value: formData.distribution_designation_3 || "", type: "text" },
            { label: "Employee code", value: formData.distribution_employee_code_3 || "", type: "text" },
            { label: "Bank A/C No.", value: formData.distribution_bank_ac_3 || "", type: "text" },
            { label: "Amount Rs.", value: formData.distribution_amount_3?.toString() || "", type: "text" },
            { label: "Income tax", value: formData.distribution_income_tax_3?.toString() || "", type: "text" },
            { label: "Net amount", value: formData.distribution_net_amount_3?.toString() || "", type: "text" },
            { label: "Token no.", value: formData.distribution_token_no_3 || "", type: "text" },
            { label: "Remaining amount (if any) to DDF of CEC", value: formData.remaining_amount_ddf?.toString() || "", type: "text" },
            { label: "Certified that", value: "", type: "text" },
            { label: "(a) The amount distributed is within the prescribed limit for each individual.", value: formData.certify_a ? "Checked" : "", type: "text" },
            { label: "(b1) This is interim distribution and the percentage of amount of work done against the consultancy project is not less than the corresponding percentage of the consultancy fee being distributed now.", value: formData.certify_b1 ? "Checked" : "", type: "text" },
            { label: "(b2) This is final distribution and that the work has been completed. The final report has been sent vide letter No. __________ Dated __________ (Copy enclosed)", value: formData.certify_b2 ? "Checked" : "", type: "text" },
            { label: "The following documents will be required at the closing time of the course in CD/Pen-Drive:", value: "", type: "text" },
            { label: "1. Name and address, phone, fax etc. of the sponsoring agency.", value: "", type: "text" },
            { label: "2. List of the internal and outside faculty/experts with address", value: "", type: "text" },
            { label: "3. List of the participants with full address.", value: "", type: "text" },
            { label: "4. Time Table copy", value: "", type: "text" },
            { label: "5. Copy of the group-photo.", value: "", type: "text" },
            { label: "Signature of the Course Coordinator (with date)", value: "", type: "text" },
            { label: "Extn. (O)", value: formData.coordinator_extn || "", type: "text" },
            { label: "Mobile", value: formData.coordinator_mobile || "", type: "text" },
            { label: "Email :", value: formData.coordinator_email || "", type: "text" },
            { label: "Endorsement by CEC /SRIC Office, I.I.T. Roorkee", value: "", type: "text" },
            { label: "The above is submitted for approval as recommended by Course Coordinator", value: "", type: "text" },
            { label: "Recommended/Not Recommended", value: "", type: "text" },
            { label: "Approved/Not Approved", value: "", type: "text" },
            { label: "D.A. /Sr.Supdt. C.E.C.", value: "", type: "text" },
            { label: "Coordinator, CEC", value: "", type: "text" },
            { label: "D.A. /Supdt. SRIC", value: "", type: "text" },
            { label: "A.R./Dy. Registrar (SRIC)", value: "", type: "text" },
            { label: "Dean, SRIC", value: "", type: "text" },
            { label: "For distribution of total Institute share into IDF/CEC Account . DDF, PDF and incentive to staff, SWF etc. on getting full payment only at the time of closing the project (on final distribution only):", value: "", type: "text" },
            { label: "Total Institute Share deducted (P)", value: formData.total_institute_share?.toString() || "", type: "text" },
            { label: "(a) RDF (CEC Account ) [CED-IDF-001]", value: "", type: "text" },
            { label: "50% of P", value: formData.rdf_50_percent?.toString() || "", type: "text" },
            { label: "(b) DDF of CEC [CEC-DDF-001]", value: "", type: "text" },
            { label: "15% of P", value: formData.ddf_15_percent?.toString() || "", type: "text" },
            { label: "(c) Electricity Charges [CEC-DDF-001]", value: "", type: "text" },
            { label: "5% of P", value: formData.electricity_5_percent?.toString() || "", type: "text" },
            { label: "(d) PDF", value: "", type: "text" },
            { label: "25 % of P", value: formData.pdf_25_percent?.toString() || "", type: "text" },
            { label: "(i) PDF of Dr. ", value: formData.pdf_dr_1?.toString() || "", type: "text" },
            { label: "(ii) PDF of Dr. ", value: formData.pdf_dr_2?.toString() || "", type: "text" },
            { label: "(iii) PDF of Dr. ", value: formData.pdf_dr_3?.toString() || "", type: "text" },
            { label: "Total", value: formData.pdf_total?.toString() || "", type: "text" },
            { label: "Distribution of incentive to office staff and SWF etc. ...5.% etc. ........ of P", value: formData.incentive_distribution?.toString() || "", type: "text" },
            { label: "(i) Staff Welfare Fund", value: "", type: "text" },
            { label: "(5%)", value: formData.staff_welfare_5_percent?.toString() || "", type: "text" },
            { label: "(ii) Departmental Office", value: "", type: "text" },
            { label: "(20%)", value: formData.departmental_office_20_percent?.toString() || "", type: "text" },
            { label: "(iii) CEC Staff", value: "", type: "text" },
            { label: "(30%)", value: formData.cec_staff_30_percent?.toString() || "", type: "text" },
            { label: "(iv) Fund for Community Activities", value: "", type: "text" },
            { label: "(10%)", value: formData.community_activities_10_percent?.toString() || "", type: "text" },
            { label: "(v) Central Administrative Fund", value: "", type: "text" },
            { label: "(35%)", value: formData.central_admin_35_percent?.toString() || "", type: "text" },
            { label: "(Signature of Course Coordinator)", value: "", type: "text" },
            { label: "No. CEC/", value: formData.cec_number || "", type: "text" },
            { label: "Dated:", value: formData.cec_dated || "", type: "text" },
            { label: "Copy forwarded for taking further action to:", value: "", type: "text" },
            { label: "1. Professor & Head", value: "", type: "text" },
            { label: "2. Principal Investigator", value: "", type: "text" },
            { label: "3. Professor-in-Charge (Finance) O.S. Pay roll for information and n.a. please", value: "", type: "text" },
            { label: "4. Section In charge, CEC", value: "", type: "text" },
            { label: "5. Distribution Folder", value: "", type: "text" },
            { label: "Coordinator, CEC", value: "", type: "text" }
        ],
        multilineFields: []
    };
};
