import { FormConfig } from './route';

export const courseApprovalOldConfig: FormConfig = {
    title: "REQUEST FOR APPROVAL OF HRD / CONSULTANCY COURSE",
    subtitle: undefined,
    fields: [
        { label: "1. Name of the P.I. :", value: "", type: "text" },
        { label: "Desgn:", value: "", type: "text" },
        { label: "Deptt./Centre:", value: "", type: "text" },
        { label: "2. Title of the Course:", value: "", type: "text" },
        { label: "3. Type of Sponsorship:", value: "", type: "text" },
        { label: "Specify if others:", value: "", type: "text" },
        { label: "4. Name and Address of Sponsor's with GST Details :", value: "", type: "multiline" },
        { label: "5. GST details", value: "", type: "text" },
        { label: "6. Payment to be received in:", value: "", type: "text" },
        { label: "7. Date of Commencement:", value: "", type: "text" },
        { label: "Expected date of Completion:", value: "", type: "text" },
        { label: "8. Details of Faculty/Staff who shall be associated:", value: "", type: "text" },
        { label: "Name of faculty", value: "", type: "subfield", indentLevel: 1 },
        { label: "Designation", value: "", type: "subfield", indentLevel: 1 },
        { label: "Employees No.", value: "", type: "subfield", indentLevel: 1 },
        { label: "Department/Centre", value: "", type: "subfield", indentLevel: 1 },
        { label: "Signature", value: "", type: "subfield", indentLevel: 1 },
        { label: "Technical Staff", value: "", type: "subfield", indentLevel: 1 },
        { label: "Designation", value: "", type: "subfield", indentLevel: 1 },
        { label: "Employee No.", value: "", type: "subfield", indentLevel: 1 },
        { label: "Department / Centre", value: "", type: "subfield", indentLevel: 1 },
        { label: "8. Budget (should conform to the contract/agreement with the sponsor) :", value: "", type: "text" },
        { label: "1. Gross amount including service Tax = (G) received", value: "", type: "text" },
        { label: "2. Less GST as applicable (presently GST @ 18%) (L)", value: "", type: "text" },
        { label: "3. (a) Contracted amount T = (G – L)", value: "", type: "text" },
        { label: "(b) Institute Share in the beginning (P) (20% of T)", value: "", type: "text" },
        { label: "4. Honorarium to outside/internal experts", value: "", type: "text" },
        { label: "5. Expenses on:", value: "", type: "text" },
        { label: "(i) Course design and material development", value: "", type: "subfield", indentLevel: 1 },
        { label: "(ii) Cost of registration course material (stationery, pen pad, bags, Xeroxing, typing etc.)", value: "", type: "subfield", indentLevel: 1 },
        { label: "(iii) Contingency / miscellaneous expenses", value: "", type: "subfield", indentLevel: 1 },
        { label: "(iv) Infrastructure charges including hall and equipment charges", value: "", type: "subfield", indentLevel: 1 },
        { label: "(v) Accommodation, boarding and lodging", value: "", type: "subfield", indentLevel: 1 },
        { label: "(vi) Transportation: TA / DA to outside experts/participants", value: "", type: "subfield", indentLevel: 1 },
        { label: "(vii) Local travel / field trip / tour", value: "", type: "subfield", indentLevel: 1 },
        { label: "(viii) Research /Office Staff (if required please specify)", value: "", type: "subfield", indentLevel: 1 },
        { label: "6. If any", value: "", type: "text" },
        { label: "9. Other relevant information (attach sheet, if necessary)", value: "", type: "text" },
        { label: "i) Correspondence with sponsor", value: "", type: "text" },
        { label: "ii) Request letter for special approval, if any", value: "", type: "text" },
        { label: "iii) Bank Draft /Transaction No.__________ dated ___________ of Rs.___________", value: "", type: "text" },
        { label: "The following documents will be required at the closing time of course in CD /Pen-Drive:", value: "", type: "text" },
        { label: "(1) Name, address, phone, fax etc. of the sponsoring agency (2) List of internal and external faculty / experts with address (3) List of the participants with full address (5) Time table copy, (6) Soft / hard copy of the group-photo.", value: "", type: "text" },
        { label: "Signature of the Course Coordinator (with date)", value: "", type: "text" },
        { label: "Extn. (O)", value: "", type: "text" },
        { label: "Mobile", value: "", type: "text" },
        { label: "Email", value: "", type: "text" },
        { label: "Signature of Head of the Deptt./Centre (with date & stamp)", value: "", type: "text" },
        { label: "Endorsement by CEC Office, I.I.T. Roorkee", value: "", type: "text" },
        { label: "The above request is in accordance with the norms.", value: "", type: "text" },
        { label: "Recommended /Not Recommended", value: "", type: "text" },
        { label: "Dealing Asstt.", value: "", type: "text" },
        { label: "Sr. Superintendent, CEC", value: "", type: "text" },
        { label: "Coordinator, CEC", value: "", type: "text" },
        { label: "Endorsement by SRIC Office, I.I.T. Roorkee", value: "", type: "text" },
        { label: "The above request is in accordance with the laid down norms.", value: "", type: "text" },
        { label: "Course No.", value: "", type: "text" },
        { label: "Dated", value: "", type: "text" },
        { label: "Approved/Not Approved", value: "", type: "text" },
        { label: "D.A./Supdt.", value: "", type: "text" },
        { label: "Asstt. Registrar/Dy. Registrar (SRIC)", value: "", type: "text" },
        { label: "Dean, SRIC", value: "", type: "text" },
        { label: "Copy after approval to:", value: "", type: "text" },
        { label: "(1) Course Coordinator (2) Concerned HoD (3) Coordinator, CEC (4) AR SRIC- AC", value: "", type: "text" }
    ],
    multilineFields: [
        { label: "4. Name and Address of Sponsor's with GST Details :", value: "", maxWidth: 400 }
    ]
};

export const mapCourseApprovalOldDataToConfig = (formData: any): FormConfig => {
    return {
        ...courseApprovalOldConfig,
        fields: [
            { label: "1. Name of the P.I. :", value: formData.pi_name || "", type: "text" },
            { label: "Desgn:", value: formData.designation || "", type: "text" },
            { label: "Deptt./Centre:", value: formData.department || "", type: "text" },
            { label: "2. Title of the Course:", value: formData.course_title || "", type: "text" },
            { label: "3. Type of Sponsorship:", value: formData.sponsorship_type || "", type: "text" },
            { label: "Specify if others:", value: formData.sponsorship_others || "", type: "text" },
            { label: "4. Name and Address of Sponsor's with GST Details :", value: formData.sponsor_details || "", type: "multiline" },
            { label: "5. GST details", value: formData.gst_details ? "Attached" : "", type: "text" },
            { label: "6. Payment to be received in:", value: formData.payment_received_in || "", type: "text" },
            { label: "7. Date of Commencement:", value: formData.commencement_date || "", type: "text" },
            { label: "Expected date of Completion:", value: formData.completion_date || "", type: "text" },
            { label: "8. Details of Faculty/Staff who shall be associated:", value: "", type: "text" },
            { label: "Faculty:", value: "", type: "text" },
            { label: "Name of faculty", value: formData.faculty_name_1 || "", type: "subfield", indentLevel: 1 },
            { label: "Designation", value: formData.faculty_designation_1 || "", type: "subfield", indentLevel: 1 },
            { label: "Employees No.", value: formData.faculty_employee_no_1 || "", type: "subfield", indentLevel: 1 },
            { label: "Department/Centre", value: formData.faculty_department_1 || "", type: "subfield", indentLevel: 1 },
            { label: "Signature", value: formData.faculty_signature_1 || "", type: "subfield", indentLevel: 1 },
            { label: "Name of faculty", value: formData.faculty_name_2 || "", type: "subfield", indentLevel: 1 },
            { label: "Designation", value: formData.faculty_designation_2 || "", type: "subfield", indentLevel: 1 },
            { label: "Employees No.", value: formData.faculty_employee_no_2 || "", type: "subfield", indentLevel: 1 },
            { label: "Department/Centre", value: formData.faculty_department_2 || "", type: "subfield", indentLevel: 1 },
            { label: "Signature", value: formData.faculty_signature_2 || "", type: "subfield", indentLevel: 1 },
            { label: "Technical Staff:", value: "", type: "text" },
            { label: "Technical Staff", value: formData.technical_staff_name_1 || "", type: "subfield", indentLevel: 1 },
            { label: "Designation", value: formData.technical_staff_designation_1 || "", type: "subfield", indentLevel: 1 },
            { label: "Employee No.", value: formData.technical_staff_employee_no_1 || "", type: "subfield", indentLevel: 1 },
            { label: "Department / Centre", value: formData.technical_staff_department_1 || "", type: "subfield", indentLevel: 1 },
            { label: "Technical Staff", value: formData.technical_staff_name_2 || "", type: "subfield", indentLevel: 1 },
            { label: "Designation", value: formData.technical_staff_designation_2 || "", type: "subfield", indentLevel: 1 },
            { label: "Employee No.", value: formData.technical_staff_employee_no_2 || "", type: "subfield", indentLevel: 1 },
            { label: "Department / Centre", value: formData.technical_staff_department_2 || "", type: "subfield", indentLevel: 1 },
            { label: "8. Budget (should conform to the contract/agreement with the sponsor) :", value: "", type: "text" },
            { label: "1. Gross amount including service Tax = (G) received", value: formData.gross_amount?.toString() || "", type: "text" },
            { label: "2. Less GST as applicable (presently GST @ 18%) (L)", value: formData.less_gst?.toString() || "", type: "text" },
            { label: "3. (a) Contracted amount T = (G – L)", value: formData.contracted_amount?.toString() || "", type: "text" },
            { label: "(b) Institute Share in the beginning (P) (20% of T)", value: formData.institute_share?.toString() || "", type: "text" },
            { label: "4. Honorarium to outside/internal experts", value: formData.honorarium?.toString() || "", type: "text" },
            { label: "5. Expenses on:", value: "", type: "text" },
            { label: "(i) Course design and material development", value: formData.expenses_course_design?.toString() || "", type: "subfield", indentLevel: 1 },
            { label: "(ii) Cost of registration course material (stationery, pen pad, bags, Xeroxing, typing etc.)", value: formData.expenses_registration?.toString() || "", type: "subfield", indentLevel: 1 },
            { label: "(iii) Contingency / miscellaneous expenses", value: formData.expenses_contingency?.toString() || "", type: "subfield", indentLevel: 1 },
            { label: "(iv) Infrastructure charges including hall and equipment charges", value: formData.expenses_infrastructure?.toString() || "", type: "subfield", indentLevel: 1 },
            { label: "(v) Accommodation, boarding and lodging", value: formData.expenses_accommodation?.toString() || "", type: "subfield", indentLevel: 1 },
            { label: "(vi) Transportation: TA / DA to outside experts/participants", value: formData.expenses_transportation?.toString() || "", type: "subfield", indentLevel: 1 },
            { label: "(vii) Local travel / field trip / tour", value: formData.expenses_local_travel?.toString() || "", type: "subfield", indentLevel: 1 },
            { label: "(viii) Research /Office Staff (if required please specify)", value: formData.expenses_research_staff?.toString() || "", type: "subfield", indentLevel: 1 },
            { label: "6. If any", value: formData.other_expenses?.toString() || "", type: "text" },
            { label: "9. Other relevant information (attach sheet, if necessary)", value: "", type: "text" },
            { label: "i) Correspondence with sponsor", value: formData.correspondence_attachment ? "Attached" : "", type: "text" },
            { label: "ii) Request letter for special approval, if any", value: formData.approval_letter_attachment ? "Attached" : "", type: "text" },
            { label: "iii) Bank Draft /Transaction No.__________ dated ___________ of Rs.___________", value: formData.bank_draft_transaction || "", type: "text" },
            { label: "The following documents will be required at the closing time of course in CD /Pen-Drive:", value: "", type: "text" },
            { label: "(1) Name, address, phone, fax etc. of the sponsoring agency (2) List of internal and external faculty / experts with address (3) List of the participants with full address (5) Time table copy, (6) Soft / hard copy of the group-photo.", value: "", type: "text" },
            { label: "Signature of the Course Coordinator (with date)", value: "", type: "text" },
            { label: "Extn. (O)", value: formData.coordinator_extn || "", type: "text" },
            { label: "Mobile", value: formData.coordinator_mobile || "", type: "text" },
            { label: "Email", value: formData.coordinator_email || "", type: "text" },
            { label: "Signature of Head of the Deptt./Centre (with date & stamp)", value: "", type: "text" },
            { label: "Endorsement by CEC Office, I.I.T. Roorkee", value: "", type: "text" },
            { label: "The above request is in accordance with the norms.", value: "", type: "text" },
            { label: "Recommended /Not Recommended", value: "", type: "text" },
            { label: "Dealing Asstt.", value: "", type: "text" },
            { label: "Sr. Superintendent, CEC", value: "", type: "text" },
            { label: "Coordinator, CEC", value: "", type: "text" },
            { label: "Endorsement by SRIC Office, I.I.T. Roorkee", value: "", type: "text" },
            { label: "The above request is in accordance with the laid down norms.", value: "", type: "text" },
            { label: "Course No.", value: formData.sric_course_no || "", type: "text" },
            { label: "Dated", value: formData.sric_dated || "", type: "text" },
            { label: "Approved/Not Approved", value: "", type: "text" },
            { label: "D.A./Supdt.", value: "", type: "text" },
            { label: "Asstt. Registrar/Dy. Registrar (SRIC)", value: "", type: "text" },
            { label: "Dean, SRIC", value: "", type: "text" },
            { label: "Copy after approval to:", value: "", type: "text" },
            { label: "(1) Course Coordinator (2) Concerned HoD (3) Coordinator, CEC (4) AR SRIC- AC", value: "", type: "text" }
        ],
        multilineFields: [
            { label: "4. Name and Address of Sponsor's with GST Details :", value: formData.sponsor_details || "", maxWidth: 400 }
        ]
    };
};
