import { FormConfig } from './route';

export const remunerationOldConfig: FormConfig = {
    title: "Remuneration Form",
    subtitle: undefined,
    fields: [
        { label: "Employee No.", value: "", type: "text" },
        { label: "PAN No. :", value: "", type: "text" },
        { label: "1. Course Name and Course Code:", value: "", type: "text" },
        { label: "2. Name and Address of Expert (In capital letter)", value: "", type: "multiline" },
        { label: "Bank A/c No.:", value: "", type: "text" },
        { label: "Bank and Branch:", value: "", type: "text" },
        { label: "IFSC Code:", value: "", type: "text" },
        { label: "(i) Lecture (L)", value: "", type: "text" },
        { label: "Hours", value: "", type: "subfield", indentLevel: 1 },
        { label: "Date", value: "", type: "subfield", indentLevel: 1 },
        { label: "RATE/HRS", value: "", type: "subfield", indentLevel: 1 },
        { label: "AMOUNT", value: "", type: "subfield", indentLevel: 1 },
        { label: "(ii) Tutorial (T)/ Practical(P)/Panel Discussion(PD)", value: "", type: "text" },
        { label: "Hours", value: "", type: "subfield", indentLevel: 1 },
        { label: "Date", value: "", type: "subfield", indentLevel: 1 },
        { label: "RATE/HRS", value: "", type: "subfield", indentLevel: 1 },
        { label: "AMOUNT", value: "", type: "subfield", indentLevel: 1 },
        { label: "3. REMUNERATION", value: "", type: "text" },
        { label: "(L)", value: "", type: "text" },
        { label: "Hours", value: "", type: "subfield", indentLevel: 1 },
        { label: "Date", value: "", type: "subfield", indentLevel: 1 },
        { label: "RATE/HRS", value: "", type: "subfield", indentLevel: 1 },
        { label: "AMOUNT", value: "", type: "subfield", indentLevel: 1 },
        { label: "(P/PD)", value: "", type: "text" },
        { label: "Hours", value: "", type: "subfield", indentLevel: 1 },
        { label: "Date", value: "", type: "subfield", indentLevel: 1 },
        { label: "RATE/HRS", value: "", type: "subfield", indentLevel: 1 },
        { label: "AMOUNT", value: "", type: "subfield", indentLevel: 1 },
        { label: "(L/N)Lecture Notes", value: "", type: "text" },
        { label: "Hours", value: "", type: "subfield", indentLevel: 1 },
        { label: "Date", value: "", type: "subfield", indentLevel: 1 },
        { label: "RATE/HRS", value: "", type: "subfield", indentLevel: 1 },
        { label: "AMOUNT", value: "", type: "subfield", indentLevel: 1 },
        { label: "TOTAL", value: "", type: "text" },
        { label: "(Amount in words ......................................................................................................................................)", value: "", type: "text" },
        { label: "BILL VERIFIED", value: "", type: "text" },
        { label: "Signature", value: "", type: "text" },
        { label: "COURSE CO-ORDINATOR(S)", value: "", type: "text" },
        { label: "Passed for Payment for Rs. .........................", value: "", type: "text" },
        { label: "(Rupees : .................................................)", value: "", type: "text" },
        { label: "Please debit to Course A/C No. ............................", value: "", type: "text" },
        { label: "Ledger Course No. ..........................................", value: "", type: "text" },
        { label: "Date", value: "", type: "text" },
        { label: "Asstt/Supdt.", value: "", type: "text" },
        { label: "Coordinator, CEC", value: "", type: "text" },
        { label: "For Office Use:", value: "", type: "text" },
        { label: "(i) Rs. ..................................... to Sri ....................................", value: "", type: "text" },
        { label: "(ii) Rs. .................................... To Tax collected by A/C IITR", value: "", type: "text" },
        { label: "Chargeable Head/Course", value: "", type: "text" },
        { label: "Paid by Cheque no.............................. Dated ..............................section In charge", value: "", type: "text" }
    ],
    multilineFields: [
        { label: "2. Name and Address of Expert (In capital letter)", value: "", maxWidth: 400 }
    ]
};

export const mapRemunerationOldDataToConfig = (formData: any): FormConfig => {
    return {
        ...remunerationOldConfig,
        fields: [
            { label: "Employee No.", value: formData.employee_no || "", type: "text" },
            { label: "PAN No. :", value: formData.pan_no || "", type: "text" },
            { label: "1. Course Name and Course Code:", value: formData.course_name_code || "", type: "text" },
            { label: "2. Name and Address of Expert (In capital letter)", value: formData.expert_details || "", type: "multiline" },
            { label: "Bank A/c No.:", value: formData.bank_ac_no || "", type: "text" },
            { label: "Bank and Branch:", value: formData.bank_branch || "", type: "text" },
            { label: "IFSC Code:", value: formData.ifsc_code || "", type: "text" },
            { label: "(i) Lecture (L)", value: "", type: "text" },
            { label: "Hours", value: formData.lecture_hours?.toString() || "", type: "subfield", indentLevel: 1 },
            { label: "Date", value: formData.lecture_date || "", type: "subfield", indentLevel: 1 },
            { label: "RATE/HRS", value: formData.lecture_rate?.toString() || "", type: "subfield", indentLevel: 1 },
            { label: "AMOUNT", value: formData.lecture_amount?.toString() || "", type: "subfield", indentLevel: 1 },
            { label: "(ii) Tutorial (T)/ Practical(P)/Panel Discussion(PD)", value: "", type: "text" },
            { label: "Hours", value: formData.tutorial_hours?.toString() || "", type: "subfield", indentLevel: 1 },
            { label: "Date", value: formData.tutorial_date || "", type: "subfield", indentLevel: 1 },
            { label: "RATE/HRS", value: formData.tutorial_rate?.toString() || "", type: "subfield", indentLevel: 1 },
            { label: "AMOUNT", value: formData.tutorial_amount?.toString() || "", type: "subfield", indentLevel: 1 },
            { label: "3. REMUNERATION", value: "", type: "text" },
            { label: "(L)", value: "", type: "text" },
            { label: "Hours", value: formData.remuneration_l_hours?.toString() || "", type: "subfield", indentLevel: 1 },
            { label: "Date", value: formData.remuneration_l_date || "", type: "subfield", indentLevel: 1 },
            { label: "RATE/HRS", value: formData.remuneration_l_rate?.toString() || "", type: "subfield", indentLevel: 1 },
            { label: "AMOUNT", value: formData.remuneration_l_amount?.toString() || "", type: "subfield", indentLevel: 1 },
            { label: "(P/PD)", value: "", type: "text" },
            { label: "Hours", value: formData.remuneration_p_hours?.toString() || "", type: "subfield", indentLevel: 1 },
            { label: "Date", value: formData.remuneration_p_date || "", type: "subfield", indentLevel: 1 },
            { label: "RATE/HRS", value: formData.remuneration_p_rate?.toString() || "", type: "subfield", indentLevel: 1 },
            { label: "AMOUNT", value: formData.remuneration_p_amount?.toString() || "", type: "subfield", indentLevel: 1 },
            { label: "(L/N)Lecture Notes", value: "", type: "text" },
            { label: "Hours", value: formData.lecture_notes_hours?.toString() || "", type: "subfield", indentLevel: 1 },
            { label: "Date", value: formData.lecture_notes_date || "", type: "subfield", indentLevel: 1 },
            { label: "RATE/HRS", value: formData.lecture_notes_rate?.toString() || "", type: "subfield", indentLevel: 1 },
            { label: "AMOUNT", value: formData.lecture_notes_amount?.toString() || "", type: "subfield", indentLevel: 1 },
            { label: "TOTAL", value: formData.total_amount?.toString() || "", type: "text" },
            { label: "(Amount in words ......................................................................................................................................)", value: formData.amount_in_words || "", type: "text" },
            { label: "BILL VERIFIED", value: "", type: "text" },
            { label: "Signature", value: "", type: "text" },
            { label: "COURSE CO-ORDINATOR(S)", value: "", type: "text" },
            { label: "Passed for Payment for Rs. .........................", value: formData.passed_for_payment || "", type: "text" },
            { label: "(Rupees : .................................................)", value: formData.rupees_in_words || "", type: "text" },
            { label: "Please debit to Course A/C No. ............................", value: formData.course_account_no || "", type: "text" },
            { label: "Ledger Course No. ..........................................", value: formData.ledger_course_no || "", type: "text" },
            { label: "Date", value: formData.payment_date || "", type: "text" },
            { label: "Asstt/Supdt.", value: "", type: "text" },
            { label: "Coordinator, CEC", value: "", type: "text" },
            { label: "For Office Use:", value: "", type: "text" },
            { label: "(i) Rs. ..................................... to Sri ....................................", value: formData.pay_to_sri || "", type: "text" },
            { label: "(ii) Rs. .................................... To Tax collected by A/C IITR", value: formData.tax_collected || "", type: "text" },
            { label: "Chargeable Head/Course", value: formData.chargeable_head || "", type: "text" },
            { label: "Paid by Cheque no.............................. Dated ..............................section In charge", value: formData.cheque_details || "", type: "text" }
        ],
        multilineFields: [
            { label: "2. Name and Address of Expert (In capital letter)", value: formData.expert_details || "", maxWidth: 400 }
        ]
    };
};
