import { FormConfig } from './route';

export const remunerationHonorariumConfig: FormConfig = {
    title: "Remuneration/Honorarium Form for Open Participation/Sponsored Course",
    subtitle: "(To be filled after the course is over)*",
    fields: [
        { label: "PAN No. :", value: "", type: "text" },
        { label: "Employee No. :", value: "", type: "text" },
        { label: "1. Course Name :", value: "", type: "text" },
        { label: "2. Batch No. :", value: "", type: "text" },
        { label: "3. Course Code :", value: "", type: "text" },
        { label: "4. Name and Address of Expert (in capital letter), Mobile No., Email :", value: "", type: "multiline" },
        { label: "(i) Lectures (L)/Interactions/*", value: "", type: "text" },
        { label: "Hours", value: "", type: "subfield", indentLevel: 1 },
        { label: "Date", value: "", type: "subfield", indentLevel: 1 },
        { label: "Amount per hour (Rs.)", value: "", type: "subfield", indentLevel: 1 },
        { label: "Total Amount (Rs.)", value: "", type: "subfield", indentLevel: 1 },
        { label: "(ii) PDF Amount (if applicable)", value: "", type: "text" },
        { label: "Hours", value: "", type: "subfield", indentLevel: 1 },
        { label: "Date", value: "", type: "subfield", indentLevel: 1 },
        { label: "Amount per hour (Rs.)", value: "", type: "subfield", indentLevel: 1 },
        { label: "Total Amount (Rs.)", value: "", type: "subfield", indentLevel: 1 },
        { label: "(Note: For the amounts in (i) to (ii) whole or part can be transferred to PDF)", value: "", type: "text" },
        { label: "(a) Amount to be transferred in A/C", value: "", type: "text" },
        { label: "(b) Amount to be transferred in PDF", value: "", type: "text" },
        { label: "(c) Bank A/c No.:", value: "", type: "text" },
        { label: "• Bank and Branch:", value: "", type: "text" },
        { label: "• IFSC Code:", value: "", type: "text" },
        { label: "(d) Amount to be transferred in CEC-DDF-001/DDF Account", value: "", type: "text" },
        { label: "(amount to be transferred if per hour rate is more than Rs. 18,000/- as mentioned at**)", value: "", type: "text" },
        { label: "BILL VERIFIED", value: "", type: "text" },
        { label: "Signature", value: "", type: "text" },
        { label: "Signature of Course Coordinator", value: "", type: "text" },
        { label: "Passed for Payment for Rs. :", value: "", type: "text" },
        { label: "Rupees :", value: "", type: "text" },
        { label: "Please debit to Course A/C No. :", value: "", type: "text" },
        { label: "Ledger Code No. :", value: "", type: "text" },
        { label: "Date", value: "", type: "text" },
        { label: "Asstt/Supdt.", value: "", type: "text" },
        { label: "Coordinator, CEC", value: "", type: "text" },
        { label: "PTO", value: "", type: "text" },
        { label: "For Office Use:", value: "", type: "text" },
        { label: "Pay (i)", value: "", type: "text" },
        { label: "Pay (ii)", value: "", type: "text" },
        { label: "to Sri", value: "", type: "text" },
        { label: "To Tax collected by A/C IITR", value: "", type: "text" },
        { label: "Paid by Cheque no", value: "", type: "text" },
        { label: "Dated", value: "", type: "text" },
        { label: "section in charge", value: "", type: "text" },
        { label: "Note :", value: "", type: "text" },
        { label: "* The honorarium to internal faculty will be distributed after completion of the course having live interactions. Before distribution of honorarium, please ensure that course feedback, schedule, list of participates with fee detail and all the payment instalments have been resolved as per the MoU/agreement terms.", value: "", type: "multiline" },
        { label: "** Total honorarium is subject to a maximum limit of Rs 18,000/- per Hr. 50% of any left-over amount from Instructor payment (i.e., any amount above Rs 18,000 x no. of Instructor hrs) will be deposited into the PDF [SRIC] of the respective faculty [to be distributed in proportion to number of lectures/interactions], while the remaining 50% will be deposited into CEC corpus for developmental activities.", value: "", type: "multiline" }
    ],
    multilineFields: [
        { label: "4. Name and Address of Expert (in capital letter), Mobile No., Email :", value: "", maxWidth: 400 },
        { label: "* The honorarium to internal faculty will be distributed after completion of the course having live interactions. Before distribution of honorarium, please ensure that course feedback, schedule, list of participates with fee detail and all the payment instalments have been resolved as per the MoU/agreement terms.", value: "", maxWidth: 400 },
        { label: "** Total honorarium is subject to a maximum limit of Rs 18,000/- per Hr. 50% of any left-over amount from Instructor payment (i.e., any amount above Rs 18,000 x no. of Instructor hrs) will be deposited into the PDF [SRIC] of the respective faculty [to be distributed in proportion to number of lectures/interactions], while the remaining 50% will be deposited into CEC corpus for developmental activities.", value: "", maxWidth: 400 }
    ]
};

export const mapRemunerationHonorariumDataToConfig = (formData: any): FormConfig => {
    return {
        ...remunerationHonorariumConfig,
        fields: [
            { label: "PAN No. :", value: formData.pan_no || "", type: "text" },
            { label: "Employee No. :", value: formData.employee_no || "", type: "text" },
            { label: "1. Course Name :", value: formData.course_name || "", type: "text" },
            { label: "2. Batch No. :", value: formData.batch_no || "", type: "text" },
            { label: "3. Course Code :", value: formData.course_code || "", type: "text" },
            { label: "4. Name and Address of Expert (in capital letter), Mobile No., Email :", value: formData.expert_details || "", type: "multiline" },
            { label: "(i) Lectures (L)/Interactions/*", value: "", type: "text" },
            { label: "Hours", value: formData.lectures_hours?.toString() || "", type: "subfield", indentLevel: 1 },
            { label: "Date", value: formData.lectures_date || "", type: "subfield", indentLevel: 1 },
            { label: "Amount per hour (Rs.)", value: formData.lectures_amount_per_hour?.toString() || "", type: "subfield", indentLevel: 1 },
            { label: "Total Amount (Rs.)", value: formData.lectures_total_amount?.toString() || "", type: "subfield", indentLevel: 1 },
            { label: "(ii) PDF Amount (if applicable)", value: "", type: "text" },
            { label: "Hours", value: formData.pdf_hours?.toString() || "", type: "subfield", indentLevel: 1 },
            { label: "Date", value: formData.pdf_date || "", type: "subfield", indentLevel: 1 },
            { label: "Amount per hour (Rs.)", value: formData.pdf_amount_per_hour?.toString() || "", type: "subfield", indentLevel: 1 },
            { label: "Total Amount (Rs.)", value: formData.pdf_total_amount?.toString() || "", type: "subfield", indentLevel: 1 },
            { label: "(Note: For the amounts in (i) to (ii) whole or part can be transferred to PDF)", value: "", type: "text" },
            { label: "(a) Amount to be transferred in A/C", value: formData.amount_to_ac || "", type: "text" },
            { label: "(b) Amount to be transferred in PDF", value: formData.amount_to_pdf || "", type: "text" },
            { label: "(c) Bank A/c No.:", value: formData.bank_account_no || "", type: "text" },
            { label: "• Bank and Branch:", value: formData.bank_and_branch || "", type: "text" },
            { label: "• IFSC Code:", value: formData.ifsc_code || "", type: "text" },
            { label: "(d) Amount to be transferred in CEC-DDF-001/DDF Account", value: formData.amount_to_cec_ddf?.toString() || "", type: "text" },
            { label: "(amount to be transferred if per hour rate is more than Rs. 18,000/- as mentioned at**)", value: "", type: "text" },
            { label: "BILL VERIFIED", value: "", type: "text" },
            { label: "Signature", value: "", type: "text" },
            { label: "Signature of Course Coordinator", value: "", type: "text" },
            { label: "Passed for Payment for Rs. :", value: formData.passed_for_payment || "", type: "text" },
            { label: "Rupees :", value: formData.rupees_in_words || "", type: "text" },
            { label: "Please debit to Course A/C No. :", value: formData.course_account_no || "", type: "text" },
            { label: "Ledger Code No. :", value: formData.ledger_code_no || "", type: "text" },
            { label: "Date", value: formData.payment_date || "", type: "text" },
            { label: "Asstt/Supdt.", value: "", type: "text" },
            { label: "Coordinator, CEC", value: "", type: "text" },
            { label: "PTO", value: "", type: "text" },
            { label: "For Office Use:", value: "", type: "text" },
            { label: "Pay (i)", value: formData.pay_i || "", type: "text" },
            { label: "Pay (ii)", value: formData.pay_ii || "", type: "text" },
            { label: "to Sri", value: formData.to_sri || "", type: "text" },
            { label: "To Tax collected by A/C IITR", value: formData.tax_collected || "", type: "text" },
            { label: "Paid by Cheque no", value: formData.cheque_no || "", type: "text" },
            { label: "Dated", value: formData.cheque_date || "", type: "text" },
            { label: "section in charge", value: "", type: "text" },
            { label: "Note :", value: "", type: "text" },
            { label: "* The honorarium to internal faculty will be distributed after completion of the course having live interactions. Before distribution of honorarium, please ensure that course feedback, schedule, list of participates with fee detail and all the payment instalments have been resolved as per the MoU/agreement terms.", value: "", type: "multiline" },
            { label: "** Total honorarium is subject to a maximum limit of Rs 18,000/- per Hr. 50% of any left-over amount from Instructor payment (i.e., any amount above Rs 18,000 x no. of Instructor hrs) will be deposited into the PDF [SRIC] of the respective faculty [to be distributed in proportion to number of lectures/interactions], while the remaining 50% will be deposited into CEC corpus for developmental activities.", value: "", type: "multiline" }
        ],
        multilineFields: [
            { label: "4. Name and Address of Expert (in capital letter), Mobile No., Email :", value: formData.expert_details || "", maxWidth: 400 },
            { label: "* The honorarium to internal faculty will be distributed after completion of the course having live interactions. Before distribution of honorarium, please ensure that course feedback, schedule, list of participates with fee detail and all the payment instalments have been resolved as per the MoU/agreement terms.", value: "", maxWidth: 400 },
            { label: "** Total honorarium is subject to a maximum limit of Rs 18,000/- per Hr. 50% of any left-over amount from Instructor payment (i.e., any amount above Rs 18,000 x no. of Instructor hrs) will be deposited into the PDF [SRIC] of the respective faculty [to be distributed in proportion to number of lectures/interactions], while the remaining 50% will be deposited into CEC corpus for developmental activities.", value: "", maxWidth: 400 }
        ]
    };
};
