import { FormConfig } from './route';

export const taLabStaffConfig: FormConfig = {
    title: "FORM FOR PAYMENT FOR TEACHING ASSISTANT/TECHNICAL ASSISTANT/LAB STAFF",
    subtitle: undefined,
    fields: [
        { label: "Course No. :", value: "", type: "text" },
        { label: "Batch No. :", value: "", type: "text" },
        { label: "Course Name & Dates:", value: "", type: "text" },
        { label: "Name of the Coordinator:", value: "", type: "text" },
        { label: "Name and details of Teaching Assistant/Technical Assistant/Lab Staff", value: "", type: "multiline" },
        { label: "S.No.", value: "", type: "text" },
        { label: "Name", value: "", type: "text" },
        { label: "Teaching Assistant/Technical Assistant/Lab Staff *", value: "", type: "text" },
        { label: "Date (Duration)", value: "", type: "text" },
        { label: "Total Hours", value: "", type: "text" },
        { label: "Rate per hour", value: "", type: "text" },
        { label: "Amount Claimed", value: "", type: "text" },
        { label: "Signature of the Course Coordinator", value: "", type: "text" },
        { label: "* The course coordinator and instructors may engage Institute Students (who may or may not be getting fellowship/assistantship) A maximum payment of Rs 5000 per hour, with total number of hours for which the payment can be made equal to number of the lecture hours in a course. Course Coordinator can also engage TA for the maximum of 20% of total number of the lecture hours in a course.", value: "", type: "multiline" },
        { label: "BILL PROFORMA (TA/Lab Staff)", value: "", type: "text" },
        { label: "1. Name :", value: "", type: "text" },
        { label: "2. Course Name :", value: "", type: "text" },
        { label: "3. Course Code :", value: "", type: "text" },
        { label: "4. Course Coordinator :", value: "", type: "text" },
        { label: "5. Department :", value: "", type: "text" },
        { label: "1. Completion of work assigned to him/her.", value: "", type: "text" },
        { label: "2. Verified and passed for payment.", value: "", type: "text" },
        { label: "3. Certified the payment is actually due and being made for the first time.", value: "", type: "text" },
        { label: "4. It is also confirm that the claimant has not been on un authorized absence during the period of above claims.", value: "", type: "text" },
        { label: "Course Coordinator", value: "", type: "text" },
        { label: "Coordinator, CEC", value: "", type: "text" },
        { label: "Particular of assignment for Teaching Assistant/Technical Assistant/Lab Staff", value: "", type: "multiline" },
        { label: "Date (Duration)", value: "", type: "text" },
        { label: "Total Hours", value: "", type: "text" },
        { label: "Rate per hour", value: "", type: "text" },
        { label: "Amount Claimed", value: "", type: "text" },
        { label: "Total Rs.", value: "", type: "text" },
        { label: "(Rupees .................................................................................... only)", value: "", type: "text" },
        { label: "Bank A/c No.:", value: "", type: "text" },
        { label: "Bank and Branch:", value: "", type: "text" },
        { label: "IFSC Code:", value: "", type: "text" },
        { label: "Email ID:", value: "", type: "text" },
        { label: "Enroll No.:", value: "", type: "text" },
        { label: "Contact No. :", value: "", type: "text" },
        { label: "Signature of the claimant (with date)", value: "", type: "text" },
        { label: "* The course coordinator and instructors may engage Institute Students (who may or may not be getting fellowship/assistantship) A maximum payment of Rs 5000 per hour, with total number of hours for which the payment can be made equal to number of the lecture hours in a course. Course Coordinator can also engage TA for the maximum of 20% of total number of the lecture hours in a course.", value: "", type: "multiline" }
    ],
    multilineFields: [
        { label: "Name and details of Teaching Assistant/Technical Assistant/Lab Staff", value: "", maxWidth: 400 },
        { label: "* The course coordinator and instructors may engage Institute Students (who may or may not be getting fellowship/assistantship) A maximum payment of Rs 5000 per hour, with total number of hours for which the payment can be made equal to number of the lecture hours in a course. Course Coordinator can also engage TA for the maximum of 20% of total number of the lecture hours in a course.", value: "", maxWidth: 400 },
        { label: "Particular of assignment for Teaching Assistant/Technical Assistant/Lab Staff", value: "", maxWidth: 400 },
        { label: "* The course coordinator and instructors may engage Institute Students (who may or may not be getting fellowship/assistantship) A maximum payment of Rs 5000 per hour, with total number of hours for which the payment can be made equal to number of the lecture hours in a course. Course Coordinator can also engage TA for the maximum of 20% of total number of the lecture hours in a course.", value: "", maxWidth: 400 }
    ]
};

export const mapTALabStaffDataToConfig = (formData: any): FormConfig => {
    return {
        ...taLabStaffConfig,
        fields: [
            { label: "Course No. :", value: formData.course_no || "", type: "text" },
            { label: "Batch No. :", value: formData.batch_no || "", type: "text" },
            { label: "Course Name & Dates:", value: formData.course_name_dates || "", type: "text" },
            { label: "Name of the Coordinator:", value: formData.coordinator_name || "", type: "text" },
            { label: "Name and details of Teaching Assistant/Technical Assistant/Lab Staff", value: formData.ta_details || "", type: "multiline" },
            { label: "S.No.", value: "1", type: "text" },
            { label: "Name", value: formData.payment_name_1 || "", type: "text" },
            { label: "Teaching Assistant/Technical Assistant/Lab Staff *", value: formData.payment_role_1 || "", type: "text" },
            { label: "Date (Duration)", value: formData.payment_date_1 || "", type: "text" },
            { label: "Total Hours", value: formData.payment_total_hours_1?.toString() || "", type: "text" },
            { label: "Rate per hour", value: formData.payment_rate_per_hour_1?.toString() || "", type: "text" },
            { label: "Amount Claimed", value: formData.payment_amount_claimed_1?.toString() || "", type: "text" },
            { label: "Signature of the Course Coordinator", value: "", type: "text" },
            { label: "* The course coordinator and instructors may engage Institute Students (who may or may not be getting fellowship/assistantship) A maximum payment of Rs 5000 per hour, with total number of hours for which the payment can be made equal to number of the lecture hours in a course. Course Coordinator can also engage TA for the maximum of 20% of total number of the lecture hours in a course.", value: "", type: "multiline" },
            { label: "BILL PROFORMA (TA/Lab Staff)", value: "", type: "text" },
            { label: "1. Name :", value: formData.proforma_name || "", type: "text" },
            { label: "2. Course Name :", value: formData.proforma_course_name || "", type: "text" },
            { label: "3. Course Code :", value: formData.proforma_course_code || "", type: "text" },
            { label: "4. Course Coordinator :", value: formData.proforma_course_coordinator || "", type: "text" },
            { label: "5. Department :", value: formData.proforma_department || "", type: "text" },
            { label: "1. Completion of work assigned to him/her.", value: "", type: "text" },
            { label: "2. Verified and passed for payment.", value: "", type: "text" },
            { label: "3. Certified the payment is actually due and being made for the first time.", value: "", type: "text" },
            { label: "4. It is also confirm that the claimant has not been on un authorized absence during the period of above claims.", value: "", type: "text" },
            { label: "Course Coordinator", value: "", type: "text" },
            { label: "Coordinator, CEC", value: "", type: "text" },
            { label: "Particular of assignment for Teaching Assistant/Technical Assistant/Lab Staff", value: formData.proforma_particulars || "", type: "multiline" },
            { label: "Date (Duration)", value: formData.proforma_date || "", type: "text" },
            { label: "Total Hours", value: formData.proforma_total_hours?.toString() || "", type: "text" },
            { label: "Rate per hour", value: formData.proforma_rate_per_hour?.toString() || "", type: "text" },
            { label: "Amount Claimed", value: formData.proforma_amount_claimed?.toString() || "", type: "text" },
            { label: "Total Rs.", value: formData.total_rs?.toString() || "", type: "text" },
            { label: "(Rupees .................................................................................... only)", value: "", type: "text" },
            { label: "Bank A/c No.:", value: formData.bank_ac_no || "", type: "text" },
            { label: "Bank and Branch:", value: formData.bank_branch || "", type: "text" },
            { label: "IFSC Code:", value: formData.ifsc_code || "", type: "text" },
            { label: "Email ID:", value: formData.email_id || "", type: "text" },
            { label: "Enroll No.:", value: formData.enroll_no || "", type: "text" },
            { label: "Contact No. :", value: formData.contact_no || "", type: "text" },
            { label: "Signature of the claimant (with date)", value: "", type: "text" },
            { label: "* The course coordinator and instructors may engage Institute Students (who may or may not be getting fellowship/assistantship) A maximum payment of Rs 5000 per hour, with total number of hours for which the payment can be made equal to number of the lecture hours in a course. Course Coordinator can also engage TA for the maximum of 20% of total number of the lecture hours in a course.", value: "", type: "multiline" }
        ],
        multilineFields: [
            { label: "Name and details of Teaching Assistant/Technical Assistant/Lab Staff", value: formData.ta_details || "", maxWidth: 400 },
            { label: "* The course coordinator and instructors may engage Institute Students (who may or may not be getting fellowship/assistantship) A maximum payment of Rs 5000 per hour, with total number of hours for which the payment can be made equal to number of the lecture hours in a course. Course Coordinator can also engage TA for the maximum of 20% of total number of the lecture hours in a course.", value: "", maxWidth: 400 },
            { label: "Particular of assignment for Teaching Assistant/Technical Assistant/Lab Staff", value: formData.proforma_particulars || "", maxWidth: 400 },
            { label: "* The course coordinator and instructors may engage Institute Students (who may or may not be getting fellowship/assistantship) A maximum payment of Rs 5000 per hour, with total number of hours for which the payment can be made equal to number of the lecture hours in a course. Course Coordinator can also engage TA for the maximum of 20% of total number of the lecture hours in a course.", value: "", maxWidth: 400 }
        ]
    };
};
