/**
 * Past courses data by academic year.
 * Replace placeholder entries with actual data from the PDFs for each year.
 */
export type PastCourse = {
  sno: number;
  department: string;
  course: string;
  coordinator: string;
  duration: string;
  sponsor: string;
};

const PAST_COURSES: Record<string, PastCourse[]> = {
  "2024-25": [
    { sno: 1, department: "Computer Science & Engineering", course: "Big Data Analytics, Batch - I", coordinator: "Prof. Partha Pratim Roy", duration: "April 01-26, 2024", sponsor: "National Telecommunications Institute, Ghaziabad" },
    { sno: 2, department: "Civil Engineering", course: "Mix Design Concepts and Quality Control Practices in Pavement Construction", coordinator: "Prof. Nikhil Saboo", duration: "April 4-7, 2024", sponsor: "Open IITR Participation" },
    { sno: 3, department: "Water Resources Development & Management", course: "Water, Built Environment and Emergency Preparedness, Batch 01", coordinator: "Pro. Mohit P. Mohanty", duration: "April 16 - 19, 2024", sponsor: "National Health Mission, Odisha" },
    { sno: 4, department: "Department of Management Studies", course: "Data Analytics and Machine Learning using Business Intelligence Tools", coordinator: "Prof. Manu Kumar Gupta, Prof. Sumit Kumar Yadav", duration: "April 22 - 26, 2024", sponsor: "Directorate of Income Tax (Systems), New Delhi" },
    { sno: 5, department: "Water Resources Development & Management", course: "Water, Built Environment and Emergency Preparedness, Batch 02", coordinator: "Pro. Mohit P. Mohanty", duration: "April 29 2024 to May 02, 2024", sponsor: "National Health Mission, Odisha" },
    { sno: 6, department: "Department of Management Studies", course: "Energy Modelling, Batch 01", coordinator: "Prof. Tarun Sharma", duration: "April 29, 2024 to May 01, 2024", sponsor: "NTPC, Power Management Institute Noida" },
    { sno: 7, department: "Water Resources Development & Management", course: "Water, Built Environment and Emergency Preparedness, Batch 03", coordinator: "Pro. Mohit P. Mohanty", duration: "May 6 - 9, 2024", sponsor: "National Health Mission, Odisha" },
    { sno: 8, department: "Department of Management Studies", course: "Data Analytics and Machine Learning using Business Intelligence Tools", coordinator: "Prof. Sumit Kumar Yadav, Prof. Manu Kumar Gupta", duration: "May 6 - 10, 2024", sponsor: "Directorate of Income Tax (Systems), New Delhi" },
    { sno: 9, department: "Computer Science & Engineering", course: "AI & Deep Learning", coordinator: "Prof. Raksha Sharma", duration: "May 6 - 10, 2024", sponsor: "IRDE Dehradun, DRDO" },
    { sno: 10, department: "Water Resources Development & Management", course: "Capacity Building of Civil Engineers of Minor Irrigation (MI) Organization Batch - 03", coordinator: "Prof. Deepak Khare", duration: "May 06-11, 2024", sponsor: "OCTDMS, Dept. of Water Resources Odisha" },
    { sno: 11, department: "Civil Engineering", course: "Advanced Concrete Technology", coordinator: "Prof. Anjaneya Dixit", duration: "May 8 - 10, 2024", sponsor: "RITES Limited, Gurgaon (Haryana)" },
    { sno: 12, department: "Civil Engineering", course: "UAV for Landslides: Learn Application of UAV in Monitoring Landslides", coordinator: "Prof. Alok Bhardwaj", duration: "May 13 - 15, 2024", sponsor: "Open" },
    { sno: 13, department: "Water Resources Development & Management", course: "Water, Built Environment and Emergency Preparedness, Batch 04", coordinator: "Pro. Mohit P. Mohanty", duration: "May 13 - 16, 2024", sponsor: "National Health Mission, Odisha" },
    { sno: 14, department: "Civil Engineering", course: "Refrigeration & Air Conditioning Applications in Military Infrastructure", coordinator: "Prof. Ravi Kumar", duration: "June 01, 2024 to October 24, 2024", sponsor: "Commander Works Engineer(CWE), Jhansi" },
    { sno: 15, department: "Water Resources Development & Management", course: "Capacity Building of Civil Engineers of Minor Irrigation (MI) Organization Batch - 04", coordinator: "Prof. Deepak Khare", duration: "June 03-08, 2024", sponsor: "OCTDMS, Dept. of Water Resources Odisha" },
    { sno: 16, department: "Continuing Education Centre", course: "My Bharat Portal & Digital Literacy, Batch - 01", coordinator: "Prof. Kaushik Ghosh", duration: "June 27, 2024", sponsor: "Mera Yuva Bharat (My Bharat), New Delhi" },
    { sno: 17, department: "Water Resources Development & Management", course: "Capacity Building of Civil Engineers of Minor Irrigation (MI) Organization Batch - 05", coordinator: "Prof. Deepak Khare", duration: "July 01-06, 2024", sponsor: "OCTDMS, Dept. of Water Resources Odisha" },
    { sno: 18, department: "Department of Management Studies", course: "Data Analytics and Machine Learning using Business Intelligence Tools", coordinator: "Prof. Sumit Kumar Yadav, Prof. Manu Kumar Gupta", duration: "July 08-12, 2024", sponsor: "Directorate of Income Tax (Systems), New Delhi" },
    { sno: 19, department: "Water Resources Development & Management", course: "Capacity Building of Civil Engineers of Minor Irrigation (MI) Organization Batch - 06", coordinator: "Prof. Deepak Khare", duration: "July 15-20, 2024", sponsor: "OCTDMS, Dept. of Water Resources Odisha" },
    { sno: 20, department: "Department of Management Studies", course: "Data Analytics and Machine Learning using Business Intelligence Tools", coordinator: "Prof. Sumit Kumar Yadav, Prof. Manu Kumar Gupta", duration: "August 05-09, 2024", sponsor: "Directorate of Income Tax (Systems), New Delhi" },
    { sno: 21, department: "Water Resources Development & Management", course: "Capacity Building of Civil Engineers of Minor Irrigation (MI) Organization Batch - 07", coordinator: "Prof. Deepak Khare", duration: "August 05-10, 2024", sponsor: "OCTDMS, Dept. of Water Resources Odisha" },
    { sno: 22, department: "Hydro and Renewable Energy Department", course: "Training of Trainers (TOT) under Jal Urja Mitra Programme", coordinator: "Prof. Arun Kumar", duration: "August 05-15, 2024", sponsor: "MNRE, Delhi" },
    { sno: 23, department: "Applied Mathematics and Scientific Computing", course: "Artificial Intelligence and Machine Learning (Batch - 01)", coordinator: "Prof. Millie Pant", duration: "August 07 - 28, 2024", sponsor: "Deloitte, Consulting India Pvt. Ltd., Hyderabad" },
    { sno: 24, department: "Applied Mathematics and Scientific Computing", course: "Artificial Intelligence and Machine Learning (Batch - 02)", coordinator: "Prof. Millie Pant", duration: "August 07 - 28, 2024", sponsor: "Deloitte, Consulting India Pvt. Ltd., Hyderabad" },
    { sno: 25, department: "Water Resources Development & Management", course: "Capacity Building of Civil Engineers of Minor Irrigation (MI) Organization Batch - 08", coordinator: "Prof. Deepak Khare", duration: "August 12-17, 2024", sponsor: "OCTDMS, Dept. of Water Resources Odisha" },
    { sno: 26, department: "Earthquake Engineering", course: "Constructive Insights Workshop on Steel and Construction Best Practices", coordinator: "Prof. P.C. Ashwin Kumar", duration: "August 21 - 23, 2024", sponsor: "Tata Tiscon" },
    { sno: 27, department: "Electrical Engineering", course: "Electricity (Power) Markets", coordinator: "Prof. Deep Kiran, Prof. Tarun Sharma", duration: "August 26 - 28, 2024", sponsor: "NTPC, Power Management Institute Noida" },
    { sno: 28, department: "Hydro and Renewable Energy Department", course: "Modelling and Simulation of Energy Systems", coordinator: "Prof. Pratham Arora, Prof. Rhythm Singh", duration: "Sept. 03-06, 2024", sponsor: "NHPC, Ltd. Faridabad" },
    { sno: 29, department: "Civil Engineering", course: "Sampling Storing and Testing Procedures for Wastewater and Sludge Quality Analysis of Sewage Treatment Plants (STP) and Faecal Sludge Treatment Plants (FSTP)", coordinator: "Prof. A.A. Kazmi", duration: "Sept. 03-05, 2024", sponsor: "National Institute of Urban Affairs, New Delhi" },
    { sno: 30, department: "Electronics & Computer Engineering", course: "Antenna Design Techniques using CST Microwave Studio", coordinator: "Prof. Utpal Dey", duration: "September 16 - 19, 2024", sponsor: "Bharat Electronics Ltd., Bengaluru" },
    { sno: 31, department: "Hydro and Renewable Energy Department", course: "Pumped Storage Projects Inception to Commissioning", coordinator: "Prof. Himanshu Jain, Prof. Mukesh Singhal", duration: "Sept. 17-20, 2024", sponsor: "NHPC, Ltd. Faridabad" },
    { sno: 32, department: "Civil Engineering", course: "New Technologies for Decentralized Treatment of Sewage and Sludge Management", coordinator: "Prof. A.A. Kazmi", duration: "Sept. 23-24, 2024", sponsor: "National Mission for Clean Ganga (NMCG), New Delhi" },
    { sno: 33, department: "Electronics & Computer Engineering", course: "RF Measurement Techniques", coordinator: "Prof. Utpal Dey", duration: "September 23 - 25, 2024", sponsor: "Bharat Electronics Ltd., Bengaluru" },
    { sno: 34, department: "Hydro and Renewable Energy Department", course: "Keys Drivers for Hydropower and Measures for Reduction in Cost & Tariff of Hydro Power for its Viability in current Scenario of High Penetration of Renewable Energy", coordinator: "Prof. Himanshu Jain, Prof. Rhythm Singh", duration: "October 24-26, 2024", sponsor: "NHPC, Ltd. Faridabad" },
    { sno: 35, department: "Computer Science & Engineering", course: "Advanced Training Programme in Microservices Architecture & Dev ops., Batch - 01", coordinator: "Prof. Partha Pratim Roy", duration: "November 04-08, 2024", sponsor: "National Informatics Centre, New Delhi" },
    { sno: 36, department: "Hydro and Renewable Energy Department", course: "Renewable Energy Transition including Role of Hydropower in India's Transition to Net-Zero Carbon Energy Systems", coordinator: "Prof. Rhythm Singh", duration: "Nov. 5-8, 2024", sponsor: "NHPC, Ltd. Faridabad" },
    { sno: 37, department: "Hydro and Renewable Energy Department", course: "National Hydrogen Mission & Green Hydrogen Policy", coordinator: "Prof. Pratham Arora", duration: "Nov. 11-14, 2024", sponsor: "NHPC, Ltd. Faridabad" },
    { sno: 38, department: "Computer Science & Engineering", course: "Advanced Training Programme in Microservices Architecture & Dev ops., Batch - 02", coordinator: "Prof. Partha Pratim Roy", duration: "November 18-22, 2024", sponsor: "National Informatics Centre, New Delhi" },
    { sno: 39, department: "Electronics & Computer Engineering", course: "Advanced Mobile Communications", coordinator: "Prof. Ekant Sharma", duration: "Nov. 18-22, 2024", sponsor: "Ministry of Communications, Department of Telecommunications, National Communications Academy, Ghaziabad" },
    { sno: 40, department: "Hydro and Renewable Energy Department", course: "Energy Transition & Hydrogen Economy", coordinator: "Prof. Amit C. Bhosale", duration: "Nov. 19-22, 2024", sponsor: "NHPC, Ltd. Faridabad" },
    { sno: 41, department: "Department of Management Studies", course: "Creativity Crusaders (Batch I)", coordinator: "Prof. Rajat Agrawal", duration: "Nov. 25-27, 2024", sponsor: "Bharat Electronics Ltd., Bengaluru" },
    { sno: 42, department: "Department of Management Studies", course: "Artificial Intelligence/Machine Learning", coordinator: "Prof. Gaurav Dixit", duration: "December 02-06, 2024", sponsor: "Bharat Electronics Ltd., Bengaluru" },
    { sno: 43, department: "Department of Management Studies", course: "Creativity Crusaders (Batch II)", coordinator: "Prof. Rajat Agrawal", duration: "December 04-06, 2024", sponsor: "Bharat Electronics Ltd., Bengaluru" },
    { sno: 44, department: "Computer Science & Engineering", course: "Current Topics in Cyber Security", coordinator: "Prof. Sugata Gangopadhyay", duration: "December 13-17, 2024", sponsor: "Ministry of Electronics and Information Technology, New Delhi" },
    { sno: 45, department: "Continuing Education Centre", course: "Mathematics Teachers of PM SHRI Schools of Navodaya Vidyalaya Samiti (NVS)", coordinator: "Prof. Kaushik Ghosh", duration: "Dec. 16-20, 2024", sponsor: "Navodaya Vidyalaya Samiti (NVS)" },
    { sno: 46, department: "Continuing Education Centre", course: "Science Teachers of PM SHRI Schools of Navodaya Vidyalaya Samiti (NVS)", coordinator: "Prof. Kaushik Ghosh", duration: "Dec. 23-27, 2024", sponsor: "Navodaya Vidyalaya Samiti (NVS)" },
    { sno: 47, department: "Hydro and Renewable Energy Department", course: "Solar / Wind Power Technology / Plants from Inception of Commissioning", coordinator: "Prof. C.S. Pant, Prof. Ravita Lamba", duration: "January 7-10, 2025", sponsor: "NHPC, Ltd. Faridabad" },
    { sno: 48, department: "Mechanical and Industrial Engineering Department", course: "Artificial Intelligence Applications in Plant Safety, Batch-01", coordinator: "Prof. Kaushik Pal", duration: "January 8-10, 2025", sponsor: "Maruti Suzuki India Ltd., Haryana" },
    { sno: 49, department: "Hydro and Renewable Energy Department", course: "Regulatory Framework and Operation of RE Generation Resources", coordinator: "Prof. Rhythm Singh, Prof. Himanshu Jain", duration: "January 14-17, 2025", sponsor: "NHPC, Ltd. Faridabad" },
    { sno: 50, department: "Earthquake Engineering Department", course: "Design of Steel Structure Batch -1", coordinator: "Prof. P.C. Ashwin Kumar", duration: "January 20-25, 2025", sponsor: "INSDAG Kalkata" },
    { sno: 51, department: "Hydro and Renewable Energy Department", course: "Renewable Energy: Technology Deployment, Grid Integration, Policy and Regulations", coordinator: "Prof. Himanshu Jain", duration: "January 22-31, 2025", sponsor: "Indian Oil Corporation Ltd." },
    { sno: 52, department: "Earthquake Engineering Department", course: "Constructive Insights, Batch - 02", coordinator: "Prof. P.C. Ashwin Kumar", duration: "January 27-28, 2025", sponsor: "Tata Steel" },
    { sno: 53, department: "Hydro and Renewable Energy Department", course: "Modelling and Simulation of Energy Systems", coordinator: "Prof. Rhythm Singh, Prof. Pratham Arora", duration: "January 28 -31, 2025", sponsor: "NHPC, Ltd. Faridabad" },
    { sno: 54, department: "Hydro and Renewable Energy Department", course: "Renewable Energy & Challenges of Integration with the Grid", coordinator: "Prof. Himanshu Jain, Prof. Prashant Surana", duration: "February 4-7, 2025", sponsor: "NHPC, Ltd. Faridabad" },
    { sno: 55, department: "Civil Engineering", course: "Integrated Surveying, (Batch - 1)", coordinator: "Prof. P.K. Garg", duration: "February 10-21, 2025", sponsor: "Open" },
    { sno: 56, department: "Hydro and Renewable Energy Department", course: "Latest Innovations in Energy Storage including PSPs & BESS", coordinator: "Prof. S.K. Singal, Prof. Himanshu Jain", duration: "February 11-14, 2025", sponsor: "NHPC, Ltd. Faridabad" },
    { sno: 57, department: "Hydro and Renewable Energy Department", course: "Mitigation Measures for Cavitation and Silt Erosion in Hydro Turbines", coordinator: "Prof. C.S. Pant", duration: "March 10-12, 2025", sponsor: "NHPC, Ltd. Faridabad" },
    { sno: 58, department: "Water Resources Development & Management", course: "Capacity Building of Engineers of Command Area Development of the Department of Water Resources - Odisha", coordinator: "Prof. Deepak Khare", duration: "March 17-22, 2025", sponsor: "Department of Water Resources -Odisha" },
    { sno: 59, department: "Hydro and Renewable Energy Department", course: "Training of Trainers (TOT) under Jal Urja Mitra Programme", coordinator: "Prof. Arun Kumar", duration: "March 17-27, 2025", sponsor: "Ministry of New and Renewable Energy, New Delhi" },
    { sno: 60, department: "Department of Management Studies", course: "Flipkart Augmentation of Industrial Relations", coordinator: "Prof. Santosh Rangnekar", duration: "March 24-29, 2025", sponsor: "Flipkart Internet Pvt. Ltd." },
  ],
  "2023-24": [
    { sno: 1, department: "DOMS", course: "Flipkart Augmentation of Industrial Relations", coordinator: "Prof. Santosh Rangnekar", duration: "April 24-29, 2023", sponsor: "Flipkart Internet Pvt., Karnataka" },
    { sno: 2, department: "CE", course: "New Technologies including FDR (Batch – I)", coordinator: "Prof. Praveen Kumar, Prof. G.D. Ransinchung, R.N.", duration: "June 1-3, 2023", sponsor: "PMGSY Cell, Rural Engineering Department, Lucknow (U.P.)" },
    { sno: 3, department: "DOMS", course: "Advance Inventory Management", coordinator: "Prof. Rajat Agarwal", duration: "June 13-14, 2023", sponsor: "HPCL Mittal Energy" },
    { sno: 4, department: "CE", course: "New Technologies including FDR (Batch – II)", coordinator: "Prof. Praveen Kumar, Prof. G.D. Ransinchung, R.N.", duration: "July 03-05, 2023", sponsor: "PMGSY Cell, Rural Engineering Department, Lucknow (U.P.)" },
    { sno: 5, department: "CE", course: "Short-Term Technical Course in Civil Engineering", coordinator: "Prof. Rakesh Ranjan", duration: "June 26-29, 2023", sponsor: "Tata Steel Limited, Jharkhand" },
    { sno: 6, department: "DOMS", course: "Certification Program in Electricity (Power) Markets", coordinator: "Prof. Tarun Sharma, Prof. Deep Kiran", duration: "July 31- August 02, 2023", sponsor: "NTPC, Power Management Institute, Noida" },
    { sno: 7, department: "HRED", course: "Short Term Training Course on Energy Transition and Sustainable Development", coordinator: "Prof. Arun Kumar", duration: "August 03-05, 2023", sponsor: "NHPC, Ltd. Faridabad" },
    { sno: 8, department: "DOMS", course: "Analytical Thinking for Excellent Performance", coordinator: "Prof. Rajat Agarwal", duration: "August 10-12, 2023", sponsor: "BEL, Bengaluru" },
    { sno: 9, department: "Applied Mathematics and Scientific Computing", course: "Certificate Course in Artificial Intelligence and Machine Learning", coordinator: "Prof. Millie Pant", duration: "August 21-Sept. 12, 2023", sponsor: "Deloitte, Consulting India Pvt. Ltd., Hyderabad" },
    { sno: 10, department: "HRED", course: "Short Term Training Course on Pumped Storage Projects at PMI Noida for NTPC", coordinator: "Prof. Arun Kumar", duration: "August 28-30, 2023", sponsor: "NTPC, Power Management Institute, Noida" },
    { sno: 11, department: "HRED", course: "Short Term Training Course on Renewable Energy & Challenges of Integration with the Grid", coordinator: "Prof. Himanshu Jain", duration: "Sept. 04 - 06, 2023", sponsor: "NHPC, Ltd. Faridabad" },
    { sno: 12, department: "HRED", course: "Short Term Training Programme on Pumped Storage Plant", coordinator: "Prof. Arun Kumar", duration: "Sept. 11-15, 2023", sponsor: "Getri, Vadodara" },
    { sno: 13, department: "WRD&M", course: "Recent Advances in Satellite based Technologies for Monitoring Hydro-climatological Extremes (RASTER 2023)", coordinator: "Prof. Mohit Prakash Mohanty", duration: "Sept. 11-15, 2023", sponsor: "ISRO Disaster Management Support Programme" },
    { sno: 14, department: "E&CE", course: "Programming in RISC-V Assembly Language", coordinator: "Prof. Sparsh Mittal", duration: "Sept. 18-22, 2023", sponsor: "Open" },
    { sno: 15, department: "E&CE", course: "RISC-V Assembly Language Programming", coordinator: "Prof. Sparsh Mittal", duration: "Sept. 19-22, 2023", sponsor: "Open" },
    { sno: 16, department: "HRED", course: "Impact on Grid due to High Penetration of Renewable Energy", coordinator: "Prof. Himanshu Jain", duration: "Sept. 20-22, 2023", sponsor: "NHPC, Ltd. Faridabad" },
    { sno: 17, department: "Applied Mathematics and Scientific Computing", course: "Certificate Course in Artificial Intelligence and Machine Learning (Batch - 02)", coordinator: "Prof. Millie Pant, Prof. Kusum Deep", duration: "Sept. 25, 2023 to Oct. 18, 2023", sponsor: "Deloitte, Consulting India Pvt. Ltd., Hyderabad" },
    { sno: 18, department: "DOMS", course: "Certificate Programme in Energy Analytics", coordinator: "Prof. Tarun Sharma, Prof. Deep Kiran", duration: "October 11-13, 2023", sponsor: "NTPC, Power Management Institute, Noida" },
    { sno: 19, department: "EQD", course: "Dynamic Analysis of Bridges for Earthquake & Moving Loads", coordinator: "Prof. Yogender Singh", duration: "October 16-17, 2023", sponsor: "RDSO, Lucknow" },
    { sno: 20, department: "HRED", course: "Short Term Training Course on Pumped Storage Projects", coordinator: "Prof. Himanshu Jain, Prof. Arun Kumar", duration: "Oct. 16-20, 2023", sponsor: "Hydro-projects & Quality Control, Pune" },
    { sno: 21, department: "HRED", course: "Short Term Training Course on Key drivers for Hydropower and Measures for Reduction in Cost & Tariff of Hydro Power", coordinator: "Prof. Arun Kumar", duration: "Oct. 17-19, 2023", sponsor: "NHPC, Ltd. Faridabad" },
    { sno: 22, department: "CE", course: "Design and Evaluation of Flexible Pavement - Principles and Practices (DEFP-3)", coordinator: "Prof. Nikhil Saboo", duration: "Oct. 20-22, 2023", sponsor: "3-day workshop" },
    { sno: 23, department: "WRD&M", course: "Latest Technologies in Water Sector", coordinator: "Prof. Ashish Pandey", duration: "Dec. 04-08, 2023", sponsor: "National Water Academy (NWA) Gov. of India" },
    { sno: 24, department: "MIED", course: "Advanced Program for PCBL Limited", coordinator: "Prof. Inderdeep Singh", duration: "December 18-22, 2023", sponsor: "PCBL Limited" },
    { sno: 25, department: "WRD&M", course: "Capacity Building of Civil Engineers of Minor Irrigation (MI) Organization under the Department of Water Resources, Odisha, Batch - 01", coordinator: "Prof. Deepak Khare", duration: "January 8-13, 2024", sponsor: "OCTDMS, Dept. of Water Resources Odisha" },
    { sno: 26, department: "HRED", course: "Short Term Training Course on Energy Transition and Hydrogen Economy", coordinator: "Prof. Pratham Arora", duration: "January 10 -12, 2024", sponsor: "NHPC, Ltd. Faridabad" },
    { sno: 27, department: "HRED", course: "Short Term Training Course on Solar / Wind Power Technology Plants from Inception to Commissioning", coordinator: "Prof. Rhythm Singh, Prof. C.S. Pant", duration: "January 22-24, 2024", sponsor: "NHPC, Ltd. Faridabad" },
    { sno: 28, department: "WRD&M", course: "GIS and Remote Sensing in Water Resources Project", coordinator: "Prof. Ashish Pandey", duration: "January 26-30, 2024", sponsor: "Irrigation Management Training Institute, Tamilnadu" },
    { sno: 29, department: "WRD&M", course: "Capacity Building of Civil Engineers of Minor Irrigation (MI) Organization under the Department of Water Resources, Odisha, Batch - 02", coordinator: "Prof. Deepak Khare", duration: "January 29, 2024 to February 03, 2024", sponsor: "OCTDMS, Dept. of Water Resources Odisha" },
    { sno: 30, department: "WRD&M", course: "Hydrological Data Collection Processing and Analysis for Surface Water Projects", coordinator: "Prof. S.K. Mishra", duration: "February 1-5, 2024", sponsor: "Irrigation Management Training Institute, Tamilnadu" },
    { sno: 31, department: "HRED", course: "Training of Trainers (ToT) under Jal Urja Mitra Programme", coordinator: "Prof. Arun Kumar", duration: "February 5-15, 2024", sponsor: "Ministry of New and Renewable Energy (MNRE), New Delhi" },
    { sno: 32, department: "HRED", course: "Hydro and Renewable Energy", coordinator: "Prof. Amit C. Bhosale", duration: "Feb. 26-28, 2024", sponsor: "NHPC, Ltd. Faridabad" },
    { sno: 33, department: "Applied Mathematics and Scientific Computing", course: "Certificate Course in Artificial Intelligence and Machine Learning", coordinator: "Prof. Millie Pant, Prof. Kusum Deep", duration: "Feb. 28, 2024 to March 20, 2024", sponsor: "Deloitte, Consulting India Pvt. Ltd., Hyderabad" },
    { sno: 34, department: "HRED", course: "Short Term Training Course on Innovative Concepts in Energy Storage Systems", coordinator: "Prof. Himanshu Jain", duration: "March 7-9, 2024", sponsor: "NHPC, Ltd. Faridabad" },
    { sno: 35, department: "CSE", course: "Automotive Embedded Systems: An Hands-On Approach (Batch – I)", coordinator: "Prof. Rahul Thakur", duration: "March 18-22, 2024", sponsor: "Maruti Suzuki India Limited, Gurgaon" },
    { sno: 36, department: "DOMS", course: "Flipkart Augmentation of Industrial Relations", coordinator: "Prof. Santosh Rangnekar", duration: "March 18-23, 2024", sponsor: "Flipkart Internet Pvt. Ltd." },
  ],
  "2022-23": [
    { sno: 1, department: "MIED", course: "Process and Plant Safety", coordinator: "Prof. K.B. Mishra", duration: "April 13, 2022", sponsor: "Director General of Hydrocarbons, Noida" },
    { sno: 2, department: "HRED", course: "DPR Preparation, Execution and Monitoring of the Projects under NMCG", coordinator: "Prof. Arun Kumar", duration: "May 5-7, 2022", sponsor: "National Mission for Clean Ganga, MOWR, New Delhi" },
    { sno: 3, department: "Hydrology", course: "Emerging Space Technology Applications for Compound Extremes 2022 (STAC - X 2022)", coordinator: "Prof. Ankit Agarwal", duration: "May 9 - 20, 2022", sponsor: "ISRO, Dehradun" },
    { sno: 4, department: "Hydrology", course: "Synergistic Training Program on Utilizing Scientific and Technological Infrastructure (STUTI)", coordinator: "Prof. B.K. Yadav", duration: "May 24-30, 2022", sponsor: "Amity University, U.P." },
    { sno: 5, department: "Earthquake", course: "Special Training Programme on Rail Bridge Dynamics", coordinator: "Prof. Yogendra Singh", duration: "July 18 - 21, 2022", sponsor: "RDSO, Lucknow" },
    { sno: 6, department: "WRD&M", course: "Disaster Management: Floods and Droughts", coordinator: "Prof. Deepak Khare, Prof. Kasiviswanathan", duration: "Aug. 4-6, 2022", sponsor: "Govt. ITEC Programme under the Ministry of External Affairs, New Delhi" },
    { sno: 7, department: "Mathematics", course: "Certificate Course in Artificial Intelligence and Machine Learning", coordinator: "Prof. Kusum Deep, Prof. Millie Pant", duration: "Aug. 8- Sept. 02, 2022", sponsor: "Deloitte Consulting India Pvt. Ltd., Hyderabad" },
    { sno: 8, department: "E&CE", course: "Application of SAR Technology in Disaster Management", coordinator: "Prof. Dharmendra Singh", duration: "Aug. 22-26, 2022", sponsor: "ISRO, Dehradun" },
    { sno: 9, department: "IPR Cell", course: "Introduction to Intellectual Property Rights", coordinator: "Prof. Rajat Agarwal", duration: "Aug 22 to Sep 10, 2022", sponsor: "Open" },
    { sno: 10, department: "WRD&M", course: "E-ITEC Training Programme on Water, Sanitation, and Hygiene", coordinator: "Prof. Basant Yadav", duration: "Aug. 25-27, 2022", sponsor: "Ministry of External Affairs, Gol, New Delhi" },
    { sno: 11, department: "WRD&M", course: "Applications of Remote Sensing and GIS in Agriculture", coordinator: "Prof. Mohit P. Mohanty", duration: "Sept. 1-3, 2022", sponsor: "Ministry of External affairs, DPA-II Division" },
    { sno: 12, department: "HRED", course: "Short-Term Training Course on Enhancement of Efficiency of Hydro Machines", coordinator: "Prof. R.P. Saini", duration: "Sept. 13-15, 2022", sponsor: "NHPC, Faridabad" },
    { sno: 13, department: "HRED", course: "Keys Drivers for Hydropower and measures for reduction in Cost & Tariff of Hydro Power for its viability in the current scenario of High penetration of Renewable Energy", coordinator: "Prof. Arun Kumar", duration: "Sept. 27 – 29, 2022", sponsor: "NHPC Ltd., Faridabad" },
    { sno: 14, department: "Mathematics", course: "Certificate Course in Artificial Intelligence and Machine Learning", coordinator: "Prof. Kusum Deep & Prof. Millie Pant", duration: "Oct.18 - Nov. 10, 2022", sponsor: "Deloitte Consulting India Pvt. Ltd., Hyderabad" },
    { sno: 15, department: "MIED", course: "Value Engineering & Analysis", coordinator: "Prof. Inderdeep Singh", duration: "Oct. 27-29, 2022", sponsor: "Severn Glocon Values Pvt. Ltd. Chennai" },
    { sno: 16, department: "Civil", course: "Total Quality Management including Quality Control Tests", coordinator: "Prof. Praveen Kumar", duration: "Oct. 31 - Nov. 06, 2022", sponsor: "Ministry of Road Transport & Highways Gol, New Delhi" },
    { sno: 17, department: "HRED", course: "Control of Time & Cost Overrun of Projects - Project Time & Cost Management Programmes", coordinator: "Prof. S.K. Singal", duration: "Nov. 06-08, 2022", sponsor: "NHPC Ltd., Faridabad" },
    { sno: 18, department: "Hydrology", course: "e-ITEC Training program on Emerging Technologies for water/wastewater treatment", coordinator: "Prof. Himanshu Joshi", duration: "Nov. 28-30, 2022", sponsor: "Ministry of External Affairs Development Partnership Administration" },
    { sno: 19, department: "Hydrology", course: "Short Term Training Course on Impact on Grid due high Penetration of Renewable Energy", coordinator: "Prof. Himanshu Joshi", duration: "Dec. 01-03, 2022", sponsor: "NHPC Ltd., Faridabad" },
    { sno: 20, department: "WRD&M", course: "Latest Technologies in Water Sector", coordinator: "Prof. Ashish Pandey", duration: "Dec. 05-09, 2022", sponsor: "National Water Academy, Pune" },
    { sno: 21, department: "Mathematics", course: "Certificate Course in Artificial Intelligence and Machine Learning", coordinator: "Prof. Kusum Deep & Prof. Millie Pant", duration: "Dec. 20, 2022 - Jan. 17, 2023", sponsor: "Deloitte Consulting India Pvt. Ltd., Hyderabad" },
    { sno: 22, department: "HRED", course: "Short Term Training Course on Regulatory Framework and Operation of Power Station", coordinator: "Prof. Arun Kumar", duration: "January 09-13, 2023", sponsor: "NHPC Ltd., Faridabad" },
    { sno: 23, department: "Civil", course: "Customized Training to IRCON Employees on Advance Surveying", coordinator: "Prof. Kamal Jain", duration: "January 9-13, 2023", sponsor: "IRCON International Ltd., New Delhi" },
    { sno: 24, department: "HRED", course: "Training of Trainers (ToT) under Jal Urja Mitra Programme", coordinator: "Prof. Arun Kumar", duration: "January 18-28, 2023", sponsor: "MNRE, New Delhi" },
    { sno: 25, department: "HRED", course: "Cost Effective Selection and Designs of SHP Projects", coordinator: "Prof. Arun Kumar", duration: "January 30 - February 07, 2023", sponsor: "Energy Management Centre, Thiruvananthapuram, Kerala" },
    { sno: 26, department: "WRD&M", course: "International Training Programme on Water Transmission and Distribution Engineering", coordinator: "Prof. Basant Yadav, Prof. M.L. Kansal", duration: "Feb. 14-17, 2023", sponsor: "Ministry of External Affairs, New Delhi" },
    { sno: 27, department: "Civil", course: "Road Safety Auditors Certification Course", coordinator: "Prof. Indrajit Ghosh", duration: "Feb. 20 - March 06, 2023", sponsor: "Ministry of Road Transport & Highways, New Delhi" },
    { sno: 28, department: "Mathematics", course: "Certificate Course in Artificial Intelligence and Machine Learning", coordinator: "Prof. Kusum Deep & Prof. Millie Pant", duration: "Feb. 28 - March 23, 2023", sponsor: "Deloitte Consulting India Pvt. Ltd., Hyderabad" },
    { sno: 29, department: "IPR Cell", course: "Creativity, Innovation and Intellectual Property Rights", coordinator: "Prof. Rajat Agarwal", duration: "March 01-22, 2023", sponsor: "Open" },
    { sno: 30, department: "Hydrology", course: "Hydrological Analysis and Planning for the Hydro and Thermal Power Projects", coordinator: "Prof. N.K. Goel", duration: "March 13-17, 2023", sponsor: "NTPC Limited, Noida" },
    { sno: 31, department: "WRD&M", course: "International Training Programme on River Engineering and Management", coordinator: "Prof. Mohit P. Mohanty, Prof. Ashish Pandey", duration: "March 13-15, 2023", sponsor: "Ministry of External Affairs, New Delhi" },
    { sno: 32, department: "E&CE", course: "Advanced Computer Architecture", coordinator: "Prof. Sparsh Mittal", duration: "March 15-30, 2023", sponsor: "Qualcomm India Pvt. Ltd., Hyderabad" },
    { sno: 33, department: "Civil", course: "Remote Sensing & GIS Technology for Environmental Monitoring, Planning & Management", coordinator: "Prof. P.K. Garg", duration: "March 16-18, 2023", sponsor: "Central Pollution Control Board (CPCB), New Delhi" },
    { sno: 34, department: "Earthquake", course: "Earthquake Time History Analysis of Bridges", coordinator: "Prof. Yogendra Singh", duration: "March 23-24, 2023", sponsor: "Open" },
    { sno: 35, department: "Hydrology", course: "Training Program on Ecohydrology", coordinator: "Prof. Ashutosh Sharma", duration: "March 27-31, 2023", sponsor: "Ministry of External Affairs, New Delhi" },
  ],
  "2021-22": [
    { sno: 1, department: "CE", course: "Advanced Finite Element Modelling of Geotechnical Constructions", coordinator: "Dr. Akanksha Tyagi", duration: "March 25 to May 27, 2021", sponsor: "Open Course" },
    { sno: 2, department: "CE", course: "Road Safety Auditors Certification Course", coordinator: "Dr. Amit Agarwal", duration: "July 19-Aug. 2, 2021", sponsor: "Ministry of Road Transport and Highways (MoRTH) and Indian Roads Congress (IRC), New Delhi." },
    { sno: 3, department: "HRED", course: "Water, Sanitation, and Hygiene (WASH)", coordinator: "Dr. M.L. Kansal, Dr. Basant Yadav", duration: "Aug. 24-26,2021", sponsor: "MEA" },
    { sno: 4, department: "HRED", course: "RLA Services for Hydro Turbine and Hydro Generator, RLA Techniques, Laboratory Evaluation Services, Trouble Shooting Services for Hydro Plants and Uprating Studies", coordinator: "Dr. Arun Kumar", duration: "Sept. 1-3, 2021", sponsor: "NHPC" },
    { sno: 5, department: "WRD&M", course: "Int. Trg. on Application of Remote Sensing and GIS in Agriculture", coordinator: "Dr. Ashish Pandey", duration: "Sept. 1-3,2021", sponsor: "MEA" },
    { sno: 6, department: "WRD&M", course: "Disaster Management (Floods and Droughts)", coordinator: "Dr. Ashish Pandey", duration: "Sept. 13-15, 2021", sponsor: "E-Itech" },
    { sno: 7, department: "DOMS", course: "Advanced Research Methods Using R", coordinator: "Dr. Abhinava Tripathi", duration: "August 14 - 28, 2021", sponsor: "Open" },
    { sno: 8, department: "ECE", course: "Data Mining And Machine Learning For IOT Applications In Industry", coordinator: "Prof. Dheeraj Kumar", duration: "July 26-Aug. 10,2021", sponsor: "SAIL Bokaro" },
    { sno: 9, department: "HRED", course: "Online Capacity Building of Professionals From member State Bhutan on Commercial Scale Biogas Plants", coordinator: "Prof. Arun Kumar", duration: "August 23-27, 2021", sponsor: "SAARC" },
    { sno: 10, department: "CSE", course: "Internet of Things (IOT) for Smart Cities and Industries", coordinator: "Prof. Rahul Thakur", duration: "July 5-20,2021", sponsor: "SAIL Bokaro" },
    { sno: 11, department: "CSE", course: "Artificial Intelligence for Computer Vision (Elementary)", coordinator: "Prof. Partha Pratim Roy", duration: "July 12 - 16, 2021", sponsor: "AICTE (under ATAL Academy)" },
    { sno: 12, department: "CSE", course: "Artificial Intelligence for Computer Vision (Advanced)", coordinator: "Prof. Partha Pratim Roy", duration: "July 26 - 30, 2021", sponsor: "AICTE (under ATAL Academy)" },
    { sno: 13, department: "CE", course: "Introduction to Geo-Spatial Tools and Technology", coordinator: "Prof. P. K. Garg", duration: "July 26 - 30, 2021", sponsor: "AICTE (under ATAL Academy)" },
    { sno: 14, department: "HRED", course: "Renewable Energy-Emerging Technology", coordinator: "Prof. R.P. Saini, Prof. S. K. Singal", duration: "Sept. 13-17,2021", sponsor: "NHPC" },
    { sno: 15, department: "HRED", course: "Online Training of SAARC Professional on Small & Micro Hydro Power Generation", coordinator: "Prof. Arun Kumar", duration: "Sept. 13-17, 2021", sponsor: "SAARC Energy Centre, Islamabad" },
    { sno: 16, department: "WRD&M", course: "Disaster Management Floods and Droughts", coordinator: "Prof. Ashish Pandey", duration: "Sept. 13-15,2021", sponsor: "E-Itech" },
    { sno: 17, department: "HRED", course: "Advanced and Disruptive Technology Trends in Energy Sector", coordinator: "Prof. Arun Kumar", duration: "Sept. 27-29,2021", sponsor: "NHPC" },
    { sno: 18, department: "HRED", course: "Online Training of Stackholders on Power Purchase Agreement of Renewable Energy Project", coordinator: "Prof. Arun Kumar", duration: "Oct. 04-08, 2021", sponsor: "SAARC Energy Centre, Islamabad" },
    { sno: 19, department: "HRED", course: "Control of Time & Cost Overrun of Projects, Project Time & Cost Management", coordinator: "Prof. S.K. Singhal", duration: "Oct. 11-13,2021", sponsor: "NHPC" },
    { sno: 20, department: "HRED", course: "Renovation and Modernization of Power Plants (Technical challenges, regulation of CEA/CERC etc.)", coordinator: "Prof. Arun Kumar", duration: "Nov. 15-17,2021", sponsor: "NHPC" },
    { sno: 21, department: "HRED", course: "Pump Storage-Design, Operation & Integration with Renewable Energy", coordinator: "Prof. Arun Kumar", duration: "Nov 22 – 26, 2021", sponsor: "NHPC" },
    { sno: 22, department: "HRED", course: "Latest Trends in Energy Sector including Battery Energy Storage Systems, Hybrid Power Plant Solutions for providing balancing Electricity and Ancillary Services", coordinator: "Prof. R.P. Saini, Prof. S.K. Singal", duration: "Dec 01-03, 2021", sponsor: "NHPC" },
    { sno: 23, department: "EED", course: "Power System Protection Advanced", coordinator: "Dr. Manoj Tripathy", duration: "Nov. 15-17, 2021", sponsor: "NHPC" },
    { sno: 24, department: "CE", course: "Road Safety Auditors Ministry of Road Certification Course Transport & Highways", coordinator: "Prof. Pushpa Choudhary", duration: "Nov. 22 – Dec. 06, 2021", sponsor: "Ministry of Road Transport & High Ways" },
    { sno: 25, department: "HRED", course: "Regulatory Framework and Operation of Power Station", coordinator: "Prof. Arun Kumar", duration: "Dec. 06 - 10, 2021", sponsor: "NHPC" },
    { sno: 26, department: "DOMS", course: "Basic of IPR and Patent Search", coordinator: "Prof. Rajat Agarwal", duration: "Dec. 06 - 20, 2021", sponsor: "Open" },
    { sno: 27, department: "WRD&M", course: "Latest Technologies in Water Sector", coordinator: "Prof. Ashish Pandey", duration: "Dec. 20-24,2021", sponsor: "NWA" },
    { sno: 28, department: "DOMS", course: "Project Management", coordinator: "Prof. Ramesh A", duration: "Dec. 20-24,2021", sponsor: "AICTE (under ATAL Academy)" },
    { sno: 29, department: "HRED", course: "Carbon Financing Program Administration, Management, Monitoring and Coordination", coordinator: "Prof. Arun Kumar", duration: "Sept 20 – 28, 2021", sponsor: "Development Bank of Ethiopia, Addis Ababa, Ethiopia" },
    { sno: 30, department: "WRD&M", course: "Application of Simulation Modelling in Water Resources Management", coordinator: "Prof. Kasiviswanathan K. S.", duration: "Oct. 11 - 15, 2021", sponsor: "AICTE (under ATAL Academy)" },
    { sno: 31, department: "HRED", course: "Hydrogen Energy", coordinator: "Dr. Amit C. Bhosale", duration: "Nov. 02-03, 2021", sponsor: "NHPC" },
    { sno: 32, department: "HRED", course: "Renovation and Modernization of Power Plants Technical Challenges, regulation of CEA/CERC etc.", coordinator: "Prof. Arun Kumar", duration: "Nov. 15 - 17, 2021", sponsor: "NHPC" },
    { sno: 33, department: "CSE", course: "Deep Learning Image Processing with Computer Vision", coordinator: "Dr. Partha Pratim Roy", duration: "Nov. 10 - 13, 2021", sponsor: "BEL" },
    { sno: 34, department: "CSE", course: "Cloud Computing", coordinator: "Prof. Neetesh Kumar", duration: "Nov. 16 - 18, 2021", sponsor: "BEL" },
    { sno: 35, department: "HRED", course: "Assessment of Soil Erosion & Sedimentation Control in Hydro Power Projects", coordinator: "Prof. Arun Kumar", duration: "December 13-17, 2021", sponsor: "NHPC" },
    { sno: 36, department: "HRED", course: "Concept of Commissioning of Hydroelectric Power Plant", coordinator: "Prof. Arun Kumar", duration: "Jan. 17 - 19, 2022", sponsor: "NHPC" },
    { sno: 37, department: "CSE", course: "Network Technologies and Programming", coordinator: "Prof. Sandeep Kumar", duration: "Jan. 17-21, 2022", sponsor: "NIC" },
    { sno: 38, department: "CSE", course: "Software Design & Development", coordinator: "Prof. Sandeep Kumar", duration: "Jan. 04-08, 2022", sponsor: "NIC" },
    { sno: 39, department: "CSE", course: "Application of Remote Sensing and GIS Techniques for Geological Investigations", coordinator: "Prof. Ravi Sharma", duration: "Jan. 10-14, 2022", sponsor: "NHPC" },
    { sno: 40, department: "CSE", course: "Geological and Geophysical Aspects", coordinator: "Prof. Ravi Sharma", duration: "March 07-11, 2022", sponsor: "NHPC" },
    { sno: 41, department: "HRED", course: "Regulatory Framework and Operation of Power Station", coordinator: "Prof. Arun Kumar", duration: "Feb. 07-11, 2022", sponsor: "NHPC" },
    { sno: 42, department: "HRED", course: "Challenges in Hydropower: Concept to Commissioning", coordinator: "Prof. Arun Kumar", duration: "Jan. 17-19, 2022", sponsor: "NHPC" },
    { sno: 43, department: "Polymer and Process Engg.", course: "Fundamentals and Applications of Ploymers, Ploymer Composites and Adhesives", coordinator: "Prof. Gaurav Manik", duration: "Dec. 13 - 22, 2022", sponsor: "Tata Steel Ltd., Jamshedpur" },
    { sno: 44, department: "EED", course: "Development of Intelligent Power Monitoring System for Reliable Operational Strategy in Upcoming evolving Market Dyanamics", coordinator: "Prof. Dheeraj K Kathod", duration: "Jan. 17 - 19, 2022", sponsor: "NHPC" },
    { sno: 45, department: "CSE", course: "Advanced Technologies in Informatics : Network Technologies and Programming", coordinator: "Prof. Sandeep Kumar", duration: "Jan. 17 - 21, 2022", sponsor: "NIC" },
    { sno: 46, department: "CSE", course: "Advanced Technologies in Informatics : Software Design & Development", coordinator: "Prof. Sandeep Kumar", duration: "Jan. 04 - 08, 2022", sponsor: "NIC" },
    { sno: 47, department: "CE", course: "Lecture Series on Advanced Finite Element Modelling of Geotechnical Construction", coordinator: "Prof. Akanksha Tyagi", duration: "March 10, 2022 - May 26, 2022", sponsor: "N.A." },
    { sno: 48, department: "Hydrology", course: "Soil Pollutants Impact Assessment and Remediation of Contamination Sites", coordinator: "Prof. Brijesh K. Yadav", duration: "March 07 - 09, 2022", sponsor: "CPCB" },
    { sno: 49, department: "CSE", course: "Advanced Technologies in Informatics: Cloud Computing Technology - E Program", coordinator: "Prof. Sandeep Kumar", duration: "February 21 - 25, 2022", sponsor: "NIC" },
    { sno: 50, department: "CSE", course: "Advanced Technologies in Informatics: AI and Machine Learning", coordinator: "Prof. Sandeep Kumar", duration: "February 28 - March 04, 2022", sponsor: "NIC" },
    { sno: 51, department: "CSE", course: "Advanced Technologies in Informatics: Network Security - Basics", coordinator: "Prof. Sandeep Kumar", duration: "March 07 - 11, 2022", sponsor: "NIC" },
    { sno: 52, department: "CE", course: "Training at Centre of Excellence in Drone Survey, NIDEM, Delhi Cantt.", coordinator: "Prof. Kamal Jain", duration: "Feb. 28, 2022 - March 04, 2022", sponsor: "NIDEM, Delhi, Cantt." },
    { sno: 53, department: "WRD&M", course: "Technical Issue of Hydropower", coordinator: "Prof. Ashish Pandey", duration: "March 21 - 25, 2022", sponsor: "SJVN Ltd., Shimla (H.P.)" },
    { sno: 54, department: "ECE", course: "Accelerators for Deep Learning", coordinator: "Prof. Sparsh Mittal", duration: "March 22 - 28, 2022", sponsor: "Qualcomm India Pvt. Ltd., Hyderabad" },
    { sno: 55, department: "Mathematics & Applied Science and Engg.", course: "Immersive Deep-dive on Machine Learning and Algorithms", coordinator: "Prof. Kusum Deep, Prof. Millie Pant", duration: "March 03 - 10, 2022", sponsor: "Deloitte Consulting India Pvt. Ltd., Hyderabad" },
  ],
};

/** Long-term online open participation courses (second list in PDF) */
export type LongTermCourse = {
  sno: number;
  courseName: string;
  batchNo: string;
  durationStatus: string;
  from: string;
  to: string;
  partnerInstitute: string;
  coordinator: string;
};

const PAST_LONG_TERM_COURSES: Record<string, LongTermCourse[]> = {
  "2024-25": [
    { sno: 1, courseName: "AI for Managers (Self-Paced)", batchNo: "II", durationStatus: "11 months", from: "01.04.2024", to: "31.12.2024", partnerInstitute: "CloudXLab", coordinator: "Prof. Z. Rahman" },
    { sno: 2, courseName: "Accelerator for Deep Learning", batchNo: "II", durationStatus: "12 months", from: "01.04.2024", to: "31.12.2024", partnerInstitute: "CloudxLab", coordinator: "Prof. Sparsh Mittal" },
    { sno: 3, courseName: "Business Analytics for Strategic Decision Making", batchNo: "II", durationStatus: "6 months", from: "01.04.2024", to: "31.12.2024", partnerInstitute: "Simplilearn", coordinator: "Prof. Amit Updahyay" },
    { sno: 4, courseName: "Professional Certificate course in Product Management", batchNo: "II", durationStatus: "5 months", from: "13.04.2024", to: "12.09.2024", partnerInstitute: "Imarticus", coordinator: "Prof. Sourabh Arora" },
    { sno: 5, courseName: "Professional Certificate course in Human Resource Management and Analytics", batchNo: "II", durationStatus: "5 months", from: "20.04.2024", to: "30.09.2024", partnerInstitute: "Imarticus", coordinator: "Prof. R.L. Dhar" },
    { sno: 6, courseName: "PG Certificate Program in Applied Data Science & AI", batchNo: "I", durationStatus: "6 months", from: "21.09.2024", to: "31.05.2025", partnerInstitute: "Jaro", coordinator: "Prof. Abhishek Samantray" },
    { sno: 7, courseName: "PG Certificate Program in Applied Data Science & AI", batchNo: "II", durationStatus: "6 months", from: "09.11.2024", to: "30.06.2025", partnerInstitute: "Jaro", coordinator: "Prof. Abhishek Samantray" },
    { sno: 8, courseName: "Applied Finance, Credit and Crime Risk Management", batchNo: "I", durationStatus: "6 months", from: "09.08.2024", to: "08.02.2025", partnerInstitute: "Hunarho", coordinator: "Prof. Anil K. Sharma" },
    { sno: 9, courseName: "PG Certificate Course in AI, ML and Data Science", batchNo: "III", durationStatus: "12 months", from: "03.08.2024", to: "02.08.2025", partnerInstitute: "CloudXLab", coordinator: "Prof. Raksha Sharma" },
    { sno: 10, courseName: "Professional Certificate course in Human Resource Management and Analytics", batchNo: "III", durationStatus: "5 months", from: "21.09.2024", to: "01.02.2025", partnerInstitute: "Imarticus", coordinator: "Prof. R.L. Dhar" },
    { sno: 11, courseName: "PG Certificate in Data Science and Machine Learning", batchNo: "IX", durationStatus: "8 months", from: "04.09.2025", to: "14.08.2025", partnerInstitute: "TimesPro", coordinator: "Prof. Alok Bhardwaj" },
    { sno: 12, courseName: "Professional Certificate course in Digital Marketing and MarTech", batchNo: "VI", durationStatus: "4.5 months", from: "28.09.2024", to: "15.02.2025", partnerInstitute: "Imarticus", coordinator: "Prof. Kalpak Kulkarni" },
    { sno: 13, courseName: "Professional Certificate course in Product Management", batchNo: "III", durationStatus: "5 months", from: "05.10.2024", to: "28.02.2025", partnerInstitute: "Imarticus", coordinator: "Prof. Sourabh Arora" },
    { sno: 14, courseName: "Advanced certificate in Supply Chain Management & Analytics", batchNo: "VIII", durationStatus: "6 months", from: "28.09.2024", to: "15.03.2025", partnerInstitute: "Imarticus", coordinator: "Prof. Rajat Agarwal" },
    { sno: 15, courseName: "TEJAS, A VLSI Training Program", batchNo: "I", durationStatus: "8 months", from: "01.03.2025", to: "30.11.2025", partnerInstitute: "Future Tech Wizards", coordinator: "Prof. Darshak Bhatt" },
    { sno: 16, courseName: "PG Certificate in Generative AI, Agentic AI & ML Application", batchNo: "I", durationStatus: "11 months", from: "20.03.2025", to: "19.02.2026", partnerInstitute: "Futurense Technologies", coordinator: "Prof. Durga Toshniwal" },
  ],
  "2023-24": [
    { sno: 1, courseName: "VLSI Design", batchNo: "I", durationStatus: "six months (47 hours L + 60 hours hands on)", from: "June 2023", to: "Dec. 2023", partnerInstitute: "Coursera", coordinator: "Prof. Sudeb Dasgupta" },
    { sno: 2, courseName: "HRM and Analytics", batchNo: "I", durationStatus: "six months (70 hours L + 30 hours hands on)", from: "August 2023", to: "Feb. 2024", partnerInstitute: "Imarticus", coordinator: "Prof. R.L. Dhar" },
    { sno: 3, courseName: "Cyber Security", batchNo: "V", durationStatus: "six months (8 hours L + 24 hours hands on)", from: "June 2023", to: "Nov. 2023", partnerInstitute: "Imarticus", coordinator: "Prof. Sateesh K. Peddoju" },
    { sno: 4, courseName: "Project Management", batchNo: "I", durationStatus: "five months (95 hours L + 20 hours hands on)", from: "August 2023", to: "Jan. 2024", partnerInstitute: "Imarticus", coordinator: "Prof. Sourabh Arora" },
    { sno: 5, courseName: "Professional Certification in Supply Chain Management & Analytics", batchNo: "VI", durationStatus: "6 months (147 hrs)", from: "June 2023", to: "Dec. 2023", partnerInstitute: "Imarticus", coordinator: "Prof. Rajat Agrawal" },
    { sno: 6, courseName: "HR Analytics Unlocking Human Capital", batchNo: "II", durationStatus: "Six months", from: "Jan. 2023", to: "June 2023", partnerInstitute: "Simplilearn", coordinator: "Prof. Usha Lenka" },
    { sno: 7, courseName: "Business Analytics for Strategic Decision Making", batchNo: "II", durationStatus: "Six months", from: "Jan. 2023", to: "June 2023", partnerInstitute: "Simplilearn", coordinator: "Prof. A. Ramesh" },
    { sno: 8, courseName: "Business Analytics for Strategic Decision Making", batchNo: "I", durationStatus: "Six months", from: "Oct. 2023", to: "March 2024", partnerInstitute: "Simplilearn", coordinator: "Prof. Amit Updahyay" },
    { sno: 9, courseName: "DSML", batchNo: "V", durationStatus: "Six months", from: "Sept. 2023", to: "March 2024", partnerInstitute: "Coursera", coordinator: "Prof. Aditi Gangopadhyay" },
    { sno: 10, courseName: "Digital Marketing", batchNo: "III", durationStatus: "Six months (105 hours L + 24 hours hands on)", from: "July 2023", to: "Jan. 2024", partnerInstitute: "Imarticus", coordinator: "Prof. Kalpak Kulkarni" },
    { sno: 11, courseName: "Digital Marketing", batchNo: "IV", durationStatus: "Six months (105 hours L + 24 hours hands on)", from: "Oct. 2023", to: "May 2024", partnerInstitute: "Imarticus", coordinator: "Prof. Kalpak Kulkarni" },
    { sno: 12, courseName: "PGDSML", batchNo: "VIII", durationStatus: "ten months (157 hours L+135 hours handson)", from: "Feb. 2024", to: "Nov. 2024", partnerInstitute: "TimesPro", coordinator: "Prof. Alok Bhardwaj" },
    { sno: 13, courseName: "5G Technology & IoT", batchNo: "III", durationStatus: "seven months", from: "Jan. 2024", to: "July 2024", partnerInstitute: "Coursera", coordinator: "Prof. Abhay Kumar Sah" },
    { sno: 14, courseName: "Think, Design, Create: Certification Program in UI/UX", batchNo: "I", durationStatus: "Six months", from: "Feb. 2024", to: "August 2024", partnerInstitute: "TimesPro", coordinator: "Prof. Saptarshi Kolay" },
    { sno: 15, courseName: "Accelerator for Deep Learning", batchNo: "II", durationStatus: "Twelve months", from: "Jan. 2024", to: "Dec. 2024", partnerInstitute: "CloudxLab", coordinator: "Prof. Sparsh Mittal" },
    { sno: 16, courseName: "Artificial Intelligence and Deep Learning", batchNo: "III", durationStatus: "Eleven months", from: "Jan. 2024", to: "Dec. 2024", partnerInstitute: "CloudxLab", coordinator: "Prof. Raksha Sharma" },
    { sno: 17, courseName: "Digital Marketing", batchNo: "V", durationStatus: "Six months (105 hours L + 24 hours hands on)", from: "March 2024", to: "August 2024", partnerInstitute: "Imarticus", coordinator: "Prof. Kalpak Kulkarni" },
    { sno: 18, courseName: "Advanced Certificate in Supply Chain Management & Analytics", batchNo: "VII", durationStatus: "6 months (147 hrs)", from: "Feb. 2024", to: "July 2024", partnerInstitute: "Imarticus", coordinator: "Prof. Rajat Agrawal" },
  ],
  "2022-23": [
    { sno: 1, courseName: "PG Certificate in Data Science and Machine Learning", batchNo: "VI", durationStatus: "—", from: "9/4/2022", to: "9/3/2023", partnerInstitute: "TSW", coordinator: "Prof. Millie Pant" },
    { sno: 2, courseName: "Supply Chain Management and Analytics", batchNo: "III", durationStatus: "—", from: "23/04/2022", to: "31/10/2022", partnerInstitute: "Imarticus", coordinator: "Prof. Rajat Agarwal" },
    { sno: 3, courseName: "Cyber Security", batchNo: "IV", durationStatus: "—", from: "28/08/2022", to: "26/02/2023", partnerInstitute: "Imarticus", coordinator: "Prof. Satish K. Peddoju" },
    { sno: 4, courseName: "Ai for Managers (Self-Paced)", batchNo: "I", durationStatus: "—", from: "1/6/2022", to: "31/12/2022", partnerInstitute: "CloudXLab", coordinator: "Prof. Z. Rahman" },
    { sno: 5, courseName: "Digital Marketing", batchNo: "I", durationStatus: "—", from: "24/09/2022", to: "11/3/2022", partnerInstitute: "Imarticus", coordinator: "Prof. Kalpak Kulkarni" },
    { sno: 6, courseName: "Business Analytics for Strategic Decision Making", batchNo: "I", durationStatus: "—", from: "01/05/2022", to: "30/09/2022", partnerInstitute: "Simplilearn", coordinator: "Prof. A. Ramesh" },
    { sno: 7, courseName: "Artificial Intelligence and Deep Leaning", batchNo: "II", durationStatus: "—", from: "01/07/2022", to: "30/06/2023", partnerInstitute: "CloudXLab", coordinator: "Prof. Raksha Sharma" },
    { sno: 8, courseName: "Decision Making Using Data Science", batchNo: "I", durationStatus: "—", from: "17/12/2022", to: "16/11/2023", partnerInstitute: "TSW", coordinator: "Prof. A. Samantray" },
    { sno: 9, courseName: "Data Science and Machine Learning", batchNo: "II", durationStatus: "—", from: "30/4/2022", to: "25/10/2022", partnerInstitute: "Coursera", coordinator: "Prof. Sanjeev Manhas" },
    { sno: 10, courseName: "HR Analytics Unlocking Human Capital", batchNo: "I", durationStatus: "—", from: "01/09/2022", to: "28/02/2023", partnerInstitute: "Simplilearn", coordinator: "Prof. Usha Lenka" },
    { sno: 11, courseName: "PG Certificate in Data Science and Machine Learning", batchNo: "VII", durationStatus: "—", from: "05/11/2022", to: "30/09/2023", partnerInstitute: "TSW", coordinator: "Prof. Alok Bhardwaj" },
    { sno: 12, courseName: "Data Science and Machine Learning", batchNo: "III", durationStatus: "—", from: "30/9/2022", to: "31/3/2023", partnerInstitute: "Coursera", coordinator: "Prof. Sanjeev Manhas" },
    { sno: 13, courseName: "PG Certificate in Data Science and Machine Learning", batchNo: "IV", durationStatus: "—", from: "26/12/2022", to: "1/7/2023", partnerInstitute: "Coursera", coordinator: "Prof. Sanjeev Manhas" },
    { sno: 14, courseName: "Supply Chain Management and Analytics", batchNo: "IV", durationStatus: "—", from: "01/10/2022", to: "31/3/2023", partnerInstitute: "Imarticus", coordinator: "Prof. Rajat Agarwal" },
    { sno: 15, courseName: "Post Graduate Certificate in 5G Technology & IOT", batchNo: "II", durationStatus: "—", from: "15/12/2022", to: "13/6/2023", partnerInstitute: "Coursera", coordinator: "Prof. Ekant Sharma" },
    { sno: 16, courseName: "Advanced Certification in Digital Marketing and Mar Tech", batchNo: "II", durationStatus: "—", from: "4/3/2023", to: "17/7/2023", partnerInstitute: "Imarticus", coordinator: "Prof. Kalpak Kulkarni" },
    { sno: 17, courseName: "Post Graduate Certificate in Machine Learning for Finance", batchNo: "II", durationStatus: "—", from: "15/12/2022", to: "13/6/2023", partnerInstitute: "Coursera", coordinator: "Prof. Gaurav Dixit" },
    { sno: 18, courseName: "Post Graduate Certificate in VLSI Design", batchNo: "II", durationStatus: "—", from: "24/09/2022", to: "1/4/2023", partnerInstitute: "Coursera", coordinator: "Prof. Sudeb Dasgupta" },
    { sno: 19, courseName: "Post Graduate Certificate in VLSI Design", batchNo: "III", durationStatus: "—", from: "26/12/2022", to: "1/7/2023", partnerInstitute: "Coursera", coordinator: "Prof. Sudeb Dasgupta" },
    { sno: 20, courseName: "Machine Learning for Supply Chains", batchNo: "I", durationStatus: "—", from: "15/12/2022", to: "13/6/2023", partnerInstitute: "Coursera", coordinator: "Prof. Manu Gupta" },
    { sno: 21, courseName: "Supply Chain Management and Analytics", batchNo: "V", durationStatus: "—", from: "18/2/2023", to: "15/8/2023", partnerInstitute: "Imarticus", coordinator: "Prof. Rajat Agarwal" },
  ],
  "2021-22": [
    { sno: 1, courseName: "Artificial Intelligence, Banking, Financial Services, and Insurance. Batch - II", batchNo: "—", durationStatus: "May 01- Oct. 24, 2021", from: "—", to: "—", partnerInstitute: "Wiley India", coordinator: "Prof. Durga Toshniwal" },
    { sno: 2, courseName: "Data Science and Machine Learning- Batch - II", batchNo: "—", durationStatus: "May 15, 2021 – April 10, 2022", from: "—", to: "—", partnerInstitute: "Times Group (TSW)", coordinator: "Prof. Millie Pant" },
    { sno: 3, courseName: "Artificial Intelligence and Deep Learning (self paced)", batchNo: "—", durationStatus: "June 15, 2021 – Dec. 31, 2021", from: "—", to: "—", partnerInstitute: "CloudX Lab", coordinator: "Prof. Gaurav Dixit & Prof. Raksha Sharma" },
    { sno: 4, courseName: "Accelerators for Deep Learning (self paced)", batchNo: "—", durationStatus: "June 30, 2021-Nov. 2021", from: "—", to: "—", partnerInstitute: "CloudX Lab", coordinator: "Prof. Sparsh Mittal" },
    { sno: 5, courseName: "Cloud Computing & DevOps Batch I", batchNo: "—", durationStatus: "Sept. 12, 2021 - Mar 27, 2022", from: "—", to: "—", partnerInstitute: "Eckovation", coordinator: "Prof. Sateesh Kumar Peddoju" },
    { sno: 6, courseName: "MLOps", batchNo: "—", durationStatus: "Sept. 05, 2021 to Sept. 05, 2022", from: "—", to: "—", partnerInstitute: "CloudX Lab", coordinator: "Prof. Raksha Sharma" },
    { sno: 7, courseName: "Machine Learning & Deep Learning", batchNo: "—", durationStatus: "Sept. 05, 2021 to Sept. 05, 2022", from: "—", to: "—", partnerInstitute: "CloudX Lab", coordinator: "Prof. Raksha Sharma" },
    { sno: 8, courseName: "Data Science", batchNo: "—", durationStatus: "Sept. 05, 2021 to Sept. 05, 2022", from: "—", to: "—", partnerInstitute: "CloudX Lab", coordinator: "Prof. Raksha Sharma" },
    { sno: 9, courseName: "Data Science and Machine Learning – Batch-III", batchNo: "—", durationStatus: "Sept.11, 2021 to Aug. 11, 2022", from: "—", to: "—", partnerInstitute: "Times Group (TSW)", coordinator: "Prof. Millie Pant" },
    { sno: 10, courseName: "Data Science and Machine Learning – Batch-IV", batchNo: "—", durationStatus: "Oct. 23, 2021 to Sept. 25, 2022", from: "—", to: "—", partnerInstitute: "Times Group (TSW)", coordinator: "Prof. Millie Pant" },
    { sno: 11, courseName: "Artificial Intelligence, Banking, Financial Services, and Insurance. Batch - III", batchNo: "—", durationStatus: "Oct. 30, 2021 – May 14, 2022", from: "—", to: "—", partnerInstitute: "Wiley India", coordinator: "Prof. Durga Toshniwal" },
    { sno: 12, courseName: "Data Science and Machine Learning", batchNo: "—", durationStatus: "Oct. 2021 to March 2022", from: "—", to: "—", partnerInstitute: "Coursera", coordinator: "Prof. Gaurav Dixit" },
    { sno: 13, courseName: "Supply Chain Management & Analytics Batch-II", batchNo: "—", durationStatus: "Nov. 2021 -April 2022", from: "—", to: "—", partnerInstitute: "Eckovation", coordinator: "Prof. Rajat Agrawal" },
    { sno: 14, courseName: "Supply Chain Management in the Digitalized Ecosystem", batchNo: "—", durationStatus: "Nov. 2021 – Oct. 2022", from: "—", to: "—", partnerInstitute: "Eckovation", coordinator: "Prof. Rajat Agrawal" },
    { sno: 15, courseName: "Machine Learning", batchNo: "—", durationStatus: "Dec. 11, 2021-May 20, 2022", from: "—", to: "—", partnerInstitute: "Times Group (TSW)", coordinator: "Prof. Partha Pratim Roy" },
    { sno: 16, courseName: "Data Science and Machine Learning – Batch-V", batchNo: "—", durationStatus: "Jan, 15, 2022 to Nov.. 26, 2022", from: "—", to: "—", partnerInstitute: "Times Group (TSW)", coordinator: "Prof. Millie Pant" },
  ],
};

export const PAST_COURSE_YEARS = ["2024-25", "2023-24", "2022-23", "2021-22"] as const;
export type PastCourseYear = (typeof PAST_COURSE_YEARS)[number];

export function getPastCourses(year: string): PastCourse[] {
  return PAST_COURSES[year] ?? [];
}

export function getPastLongTermCourses(year: string): LongTermCourse[] {
  return PAST_LONG_TERM_COURSES[year] ?? [];
}

export function isValidPastCourseYear(year: string): year is PastCourseYear {
  return PAST_COURSE_YEARS.includes(year as PastCourseYear);
}
